In [1]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import source.parsers as parsers
import source.database as database
import importlib
import os
import glob
importlib.reload(parsers)
importlib.reload(database)
import pandas as pd

In [2]:
device = "cuda"
database_folder = "D:\\tmp\\database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

VD = database.VectorDatabase(device, database_folder)
VD.info()
VD.clear_collections()
VD.create_collection()

collections: []

`torch_dtype` is deprecated! Use `dtype` instead!

created collection: Collection(name=documents) with 0 documents

In [3]:
glob_pattern = os.path.join('.', 'data', '*')
files = glob.glob(glob_pattern)


VD.add_documents(files)

parsing [.\data\demo_textfile.txt]
parsing [.\data\HW 1 - Cave Flyer.pdf]
parsing [.\data\HW 2 - Complex Numbers.pdf]
parsing [.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf]
parsing [.\data\HW 4 - Linearization and Dynamic Response.pdf]
parsing [.\data\HW 5 - Exam 1 in Matlab.pdf]
parsing [.\data\HW 6 - Routh Array and Root Locus.pdf]
parsing [.\data\HW 7 - Design Challenges.pdf]
parsing [.\data\HW 8 - Nyquist Stability.pdf]
parsing [.\data\HW 9 - Stability Margins and Compensation.pdf]
- added 10 documents, 33 chunks

In [4]:
VD.info()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records

In [5]:
VD.get(include = ['documents', 'embeddings'])

                                      id                                           document                                          embedding
0   b620ba0a-f2d0-5893-8fb0-f5611726f076  In Congress, July 4, 1776\n\nThe unanimous Dec...  [-0.074165866, 0.04833681, -0.007595299, 0.006...
1   d00a351a-96b3-560b-8b31-f7dab9abc247  In Congress, July 4, 1776\n\nThe unanimous Dec...  [-0.023325738, 0.020089287, 0.014753894, -0.00...
2   ac16fb33-1007-5f21-badf-51326739eae1  We hold these truths to be self-evident, that ...  [-0.082173355, 0.092735216, -0.04089193, -0.00...
3   6e75dfa6-61ce-5d73-9f0b-97e593b36e70  He has forbidden his Governors to pass Laws of...  [0.00507496, 0.018376272, 0.05454693, -0.00800...
4   7f7ee21b-13c6-5bd6-927b-45ae4a2d217a  He has kept among us, in times of peace, Stand...  [-0.023129975, 0.050913908, 0.018541133, -0.09...
5   2443d291-d7bc-5b92-a554-04af388319a1  He has constrained our fellow Citizens taken C...  [-0.025116457, 0.07974055, 0.0056782593, -0.03...
6   6387ac27-fb24-5a6b-9830-4c22a1923477  We, therefore, the Representatives of the unit...  [-0.05762239, -0.027064256, 0.0042288327, -0.0...
7   278661f7-8e8d-5a6b-b0e9-3a795d3c1d75  Carnegie Mellon University 24-451: Feedback Co...  [-0.021684118, -0.014771014, -0.122736916, -0....
8   84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co...  [-0.020133954, -0.0028863503, -0.1105414, -0.0...
9   a6a533b9-7542-5de9-997e-a8bf62a2567d  Carnegie Mellon University 24-451: Feedback Co...  [0.06839771, 0.051735345, -0.07544185, -0.0258...
10  8db318ca-8016-52e1-895a-b94b73bf5866  (https://docs.google.com/spreadsheets/d/185q_o...  [-0.018426241, -0.029481959, 0.061187226, 0.00...
11  6b05026a-6866-5d10-9f05-55d96590efd0  Carnegie Mellon University 24-451: Feedback Co...  [-0.07692698, -0.0016604372, -0.016284505, -0....
12  b5d3bc77-d338-5180-965f-5f40c72baed2  Carnegie Mellon University 24-451: Feedback Co...  [-0.07692698, -0.0016604372, -0.016284505, -0....
13  31d1eafa-c729-54c6-ac3d-5255371c96e7  axis). \n7. Consider a set of points that form...  [-0.10168259, -0.034086574, -0.030255536, 0.01...
14  af0e56d4-5e39-52fb-9a06-f6bb1c058b49  Instructor: Dr. Sameer Shroff \n 3 \nmethod on...  [0.0056688013, -0.055911306, -0.04749351, -0.0...
15  7b199add-cc2e-531b-8674-4feb26904f3d  Carnegie Mellon University 24-451: Feedback Co...  [-0.0141323535, -0.057475805, -0.055988383, 0....
16  2cd378ca-b422-51cb-9571-1bd060000b9b  Carnegie Mellon University 24-451: Feedback Co...  [-0.0141323535, -0.057475805, -0.055988383, 0....
17  a15a1017-2f3c-53dd-b46b-b1e946be0626  timepoints and Nu is the number of inputs for ...  [-0.07547417, -0.059211493, -0.07448536, -0.04...
18  f2b9c5c1-9186-5c6f-a312-18e0acb3184c  the system type based on your experiments.  Ex...  [-0.051410906, -0.04399027, 0.036544923, 0.073...
19  2f69e529-3bc2-5a92-874b-b6721ac6adf4  Carnegie Mellon University 24-451: Feedback Co...  [-0.057401415, 0.006973608, 0.030054374, -0.06...
20  02ef51c4-8f87-552e-8832-f72ed1df50ef  exp| - - | | cos| ---------- | + -------------...  [-0.0816496, 0.07987987, -0.048045855, -0.0397...
21  b48ccef8-b823-580c-b6a0-bda17e9a9390  Carnegie Mellon University 24-451: Feedback Co...  [-0.05867682, -0.037061498, 0.024972377, -0.06...
22  07d9494a-ea63-53ef-8cb4-07742beb9abb  Carnegie Mellon University 24-451: Feedback Co...  [-0.05867682, -0.037061498, 0.024972377, -0.06...
23  62b4072a-1df9-55d9-a9a3-457666485e0c  G = tf(1, [1 2*b(k) 1]); \n    [y,t] = step(G)...  [-0.059614502, 0.0018890589, 0.02577557, -0.00...
24  7fc073a6-6e1e-56c1-8e0e-9cadc79ce416  Carnegie Mellon University 24-451: Feedback Co...  [-0.05130317, 0.034390483, -0.021354616, 0.014...
25  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  Carnegie Mellon University 24-451: Feedback Co...  [-0.05130317, 0.034390483, -0.021354616, 0.014...
26  fd404feb-816b-5840-b735-a1266097fa05  Carnegie Mellon University 24-451: Feedback Co...  [-0.07055521, -0.02415476, -0.015510819, 0.000...
27  a8aa1388-28e7-5e69-9266-2b9048abfce8  the left-half plane, and (3) when the poles ar...  [-0.062180832, 0.008086433, 0.03435776, 0.0502...
28  566ede87-b00d-52ae-9f8d-d8ee8b019ab8  Carnegie Mellon University 24-451: Feedback Co...  [-0.062993, 0.014999981, -0.04505118, 0.010768...
29  633cf765-5101-537d-944a-50becd881f81  Carnegie Mellon University 24-451: Feedback Co...  [-0.062993, 0.014999981, -0.04505118, 0.010768...
30  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  • # 7c only.  Use Simulink.  Hint: 𝐾1 will be ...  [-0.040167514, -0.00727528, -0.014552588, -0.0...
31  ad157204-5bfd-5c8f-b7e0-8e1091b814ab  Carnegie Mellon University 24-451: Feedback Co...  [-0.0215027, 0.0059153517, -0.011506317, -0.03...
32  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  Carnegie Mellon University 24-451: Feedback Co...  [-0.0215027, 0.0059153517, -0.011506317, -0.03...
33  83b8a84b-a11d-5cb1-b2d7-758e1d86b895  Carnegie Mellon University 24-451: Feedback Co...  [-0.07116717, 0.036914937, -0.06364246, -0.021...
34  6da8d02a-6ffa-5410-8915-cb4992b2a3e0  Carnegie Mellon University 24-451: Feedback Co...  [-0.054441657, -0.012391739, -0.028563505, -0....
35  34d76a86-10c7-52c4-b9fa-a71985820b17  Carnegie Mellon University 24-451: Feedback Co...  [-0.05223167, 0.041398577, -0.06481135, -0.050...
36  27094245-284d-571e-8e0d-4f4a1ebb03f6  Carnegie Mellon University 24-451: Feedback Co...  [-0.016858883, -0.027419813, 0.019801943, -0.0...
37  4b983cb4-395e-5079-a6f3-89783cc878ac  Carnegie Mellon University 24-451: Feedback Co...  [-0.026691657, -0.0005845015, -0.02213351, 0.0...
38  c1c38fd3-bf54-54af-b292-b4bdda4fb016  for the charge to move to), your scheme works ...  [-0.048431784, 0.021509852, -0.04523998, -0.00...
39  7cf34e95-db98-511b-ac82-8e0595b014d9  Carnegie Mellon University 24-451: Feedback Co...  [-0.07105566, -0.048309013, -0.08305864, -0.02...
40  c6566691-5068-5848-a341-39c0910c40bc  Carnegie Mellon University 24-451: Feedback Co...  [-0.07105566, -0.048309013, -0.08305864, -0.02...
41  70354a5d-490e-59e0-8973-ed82cf0995a8  Carnegie Mellon University 24-451: Feedback Co...  [-0.080636844, -0.023757288, -0.06509079, -0.0...
42  9e5afc2a-3f98-5a8b-b375-24fa92c0cd58  Carnegie Mellon University 24-451: Feedback Co...  [-0.080636844, -0.023757288, -0.06509079, -0.0...

In [6]:
results = VD.collection.query(query_texts='test', include = ['embeddings'])
df_results = database._results_to_df(results, keep_cols = ['id', 'document', 'embedding'], document_length_limit= 10)
df_results

                                     id                                          embedding
0  6387ac27-fb24-5a6b-9830-4c22a1923477  [-0.05762239, -0.027064256, 0.0042288327, -0.0...
1  6e75dfa6-61ce-5d73-9f0b-97e593b36e70  [0.00507496, 0.018376272, 0.05454693, -0.00800...
2  7f7ee21b-13c6-5bd6-927b-45ae4a2d217a  [-0.023129975, 0.050913908, 0.018541133, -0.09...
3  d00a351a-96b3-560b-8b31-f7dab9abc247  [-0.023325738, 0.020089287, 0.014753894, -0.00...
4  fd404feb-816b-5840-b735-a1266097fa05  [-0.07055521, -0.02415476, -0.015510819, 0.000...
5  a15a1017-2f3c-53dd-b46b-b1e946be0626  [-0.07547417, -0.059211493, -0.07448536, -0.04...
6  31d1eafa-c729-54c6-ac3d-5255371c96e7  [-0.10168259, -0.034086574, -0.030255536, 0.01...
7  a6a533b9-7542-5de9-997e-a8bf62a2567d  [0.06839771, 0.051735345, -0.07544185, -0.0258...
8  b620ba0a-f2d0-5893-8fb0-f5611726f076  [-0.074165866, 0.04833681, -0.007595299, 0.006...
9  8db318ca-8016-52e1-895a-b94b73bf5866  [-0.018426241, -0.029481959, 0.061187226, 0.00...

In [7]:
r = VD.collection.get(limit = 2)

database._results_to_df(r)

                                     id                                           document       source_type                                          file_hash  chunk_idx              title  N_chunks   modification_date author page_lengths           basename       creation_date                  fullpath file_ext                             source_id         upload_date
0  b620ba0a-f2d0-5893-8fb0-f5611726f076  In Congress, July 4, 1776\n\nThe unanimous Dec...     full document  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...         -1  demo_textfile.txt         0 2025-11-29 23:40:34            [8148.0]  demo_textfile.txt 2025-11-29 23:39:54  .\data\demo_textfile.txt     .txt  b620ba0a-f2d0-5893-8fb0-f5611726f076 2025-12-04 13:01:16
1  d00a351a-96b3-560b-8b31-f7dab9abc247  In Congress, July 4, 1776\n\nThe unanimous Dec...  chunked document  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...          0  demo_textfile.txt         6 2025-11-29 23:40:34            [8148.0]  demo_textfile.txt 2025-11-29 23:39:54  .\data\demo_textfile.txt     .txt  b620ba0a-f2d0-5893-8fb0-f5611726f076 2025-12-04 13:01:16

In [8]:
r = VD.collection.query(query_texts=['hello'], n_results=2)
print(VD.collection.count())
print(r)

43
{'ids': [['2443d291-d7bc-5b92-a554-04af388319a1', '6e75dfa6-61ce-5d73-9f0b-97e593b36e70']], 'embeddings': None, 'documents': [['He has constrained our fellow Citizens taken Captive on the high Seas to bear Arms against their Country, to become the executioners of their friends and Brethren, or to fall themselves by their Hands.\n\nHe has excited domestic insurrections amongst us, and has endeavoured to bring on the inhabitants of our frontiers, the merciless Indian Savages, whose known rule of warfare, is an undistinguished destruction of all ages, sexes and conditions.\n\nIn every stage of these Oppressions We have Petitioned for Redress in the most humble terms: Our repeated Petitions have been answered only by repeated injury. A Prince, whose character is thus marked by every act which may define a Tyrant, is unfit to be the ruler of a free people.\n\nNor have We been wanting in attentions to our Brittish brethren. We have warned them from time to time of attempts by their legislature to extend an unwarrantable jurisdiction over us. We have reminded them of the circumstances of our emigration and settlement here. We have appealed to their native justice and magnanimity, and we have conjured them by the ties of our common kindred to disavow these usurpations, which, would inevitably interrupt our connections and correspondence. They too have been deaf to the voice of justice and of consanguinity. We must, therefore, acquiesce in the necessity, which denounces our Separation, and hold them, as we hold the rest of mankind, Enemies in War, in Peace Friends.', 'He has forbidden his Governors to pass Laws of immediate and pressing importance, unless suspended in their operation till his Assent should be obtained; and when so suspended, he has utterly neglected to attend to them.\n\nHe has refused to pass other Laws for the accommodation of large districts of people, unless those people would relinquish the right of Representation in the Legislature, a right inestimable to them and formidable to tyrants only.\n\nHe has called together legislative bodies at places unusual, uncomfortable, and distant from the depository of their public Records, for the sole purpose of fatiguing them into compliance with his measures.\n\nHe has dissolved Representative Houses repeatedly, for opposing with manly firmness his invasions on the rights of the people.\n\nHe has refused for a long time, after such dissolutions, to cause others to be elected; whereby the Legislative powers, incapable of Annihilation, have returned to the People at large for their exercise; the State remaining in the mean time exposed to all the dangers of invasion from without, and convulsions within.\n\nHe has endeavoured to prevent the population of these States; for that purpose obstructing the Laws for Naturalization of Foreigners; refusing to pass others to encourage their migrations hither, and raising the conditions of new Appropriations of Lands.\n\nHe has obstructed the Administration of Justice, by refusing his Assent to Laws for establishing Judiciary powers.\n\nHe has made Judges dependent on his Will alone, for the tenure of their offices, and the amount and payment of their salaries.\n\nHe has erected a multitude of New Offices, and sent hither swarms of Officers to harrass our people, and eat out their substance.\n\nHe has kept among us, in times of peace, Standing Armies without the Consent of our legislatures.\n\nHe has affected to render the Military independent of and superior to the Civil power.']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'basename': 'demo_textfile.txt', 'file_hash': '85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b37210fc6e72ce7bfaa496f', 'upload_date': '2025-12-04 13:01:16', 'author': '', 'N_chunks': 6, 'modification_date': '2025-11-29 23:40:34', 'source_id': 'b620ba0a-f2d0-5893-8fb0-f5611726f076', 'chunk_idx': 4, 'creation_date': '2025-11-29 23:39:54', 'page_lengths': '(8149,)', 'id': '2443d291-d7bc-5b92-a554-04af388319a1', 'file_ext': '.txt', 'title': 'demo_textfile.txt', 'fullpath': '.\\data\\demo_textfile.txt', 'source_type': 'chunked document'}, {'chunk_idx': 2, 'file_ext': '.txt', 'file_hash': '85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b37210fc6e72ce7bfaa496f', 'id': '6e75dfa6-61ce-5d73-9f0b-97e593b36e70', 'author': '', 'fullpath': '.\\data\\demo_textfile.txt', 'title': 'demo_textfile.txt', 'page_lengths': '(8149,)', 'source_id': 'b620ba0a-f2d0-5893-8fb0-f5611726f076', 'N_chunks': 6, 'upload_date': '2025-12-04 13:01:16', 'creation_date': '2025-11-29 23:39:54', 'modification_date': '2025-11-29 23:40:34', 'basename': 'demo_textfile.txt', 'source_type': 'chunked document'}]], 'distances': [[0.8519288301467896, 0.8687845468521118]]}

In [9]:
query ="hello"
df_results = VD.search(query, k = 2)
df_results

{'ids': [['2443d291-d7bc-5b92-a554-04af388319a1', '6e75dfa6-61ce-5d73-9f0b-97e593b36e70']], 'embeddings': None, 'documents': [['He has constrained our fellow Citizens taken Captive on the high Seas to bear Arms against their Country, to become the executioners of their friends and Brethren, or to fall themselves by their Hands.\n\nHe has excited domestic insurrections amongst us, and has endeavoured to bring on the inhabitants of our frontiers, the merciless Indian Savages, whose known rule of warfare, is an undistinguished destruction of all ages, sexes and conditions.\n\nIn every stage of these Oppressions We have Petitioned for Redress in the most humble terms: Our repeated Petitions have been answered only by repeated injury. A Prince, whose character is thus marked by every act which may define a Tyrant, is unfit to be the ruler of a free people.\n\nNor have We been wanting in attentions to our Brittish brethren. We have warned them from time to time of attempts by their legislature to extend an unwarrantable jurisdiction over us. We have reminded them of the circumstances of our emigration and settlement here. We have appealed to their native justice and magnanimity, and we have conjured them by the ties of our common kindred to disavow these usurpations, which, would inevitably interrupt our connections and correspondence. They too have been deaf to the voice of justice and of consanguinity. We must, therefore, acquiesce in the necessity, which denounces our Separation, and hold them, as we hold the rest of mankind, Enemies in War, in Peace Friends.', 'He has forbidden his Governors to pass Laws of immediate and pressing importance, unless suspended in their operation till his Assent should be obtained; and when so suspended, he has utterly neglected to attend to them.\n\nHe has refused to pass other Laws for the accommodation of large districts of people, unless those people would relinquish the right of Representation in the Legislature, a right inestimable to them and formidable to tyrants only.\n\nHe has called together legislative bodies at places unusual, uncomfortable, and distant from the depository of their public Records, for the sole purpose of fatiguing them into compliance with his measures.\n\nHe has dissolved Representative Houses repeatedly, for opposing with manly firmness his invasions on the rights of the people.\n\nHe has refused for a long time, after such dissolutions, to cause others to be elected; whereby the Legislative powers, incapable of Annihilation, have returned to the People at large for their exercise; the State remaining in the mean time exposed to all the dangers of invasion from without, and convulsions within.\n\nHe has endeavoured to prevent the population of these States; for that purpose obstructing the Laws for Naturalization of Foreigners; refusing to pass others to encourage their migrations hither, and raising the conditions of new Appropriations of Lands.\n\nHe has obstructed the Administration of Justice, by refusing his Assent to Laws for establishing Judiciary powers.\n\nHe has made Judges dependent on his Will alone, for the tenure of their offices, and the amount and payment of their salaries.\n\nHe has erected a multitude of New Offices, and sent hither swarms of Officers to harrass our people, and eat out their substance.\n\nHe has kept among us, in times of peace, Standing Armies without the Consent of our legislatures.\n\nHe has affected to render the Military independent of and superior to the Civil power.']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'N_chunks': 6, 'fullpath': '.\\data\\demo_textfile.txt', 'file_ext': '.txt', 'source_id': 'b620ba0a-f2d0-5893-8fb0-f5611726f076', 'upload_date': '2025-12-04 13:01:16', 'file_hash': '85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b37210fc6e72ce7bfaa496f', 'page_lengths': '(8149,)', 'title': 'demo_textfile.txt', 'chunk_idx': 4, 'source_type': 'chunked document', 'author': '', 'modification_date': '2025-11-29 23:40:34', 'basename': 'demo_textfile.txt', 'creation_date': '2025-11-29 23:39:54', 'id': '2443d291-d7bc-5b92-a554-04af388319a1'}, {'fullpath': '.\\data\\demo_textfile.txt', 'id': '6e75dfa6-61ce-5d73-9f0b-97e593b36e70', 'N_chunks': 6, 'basename': 'demo_textfile.txt', 'source_type': 'chunked document', 'modification_date': '2025-11-29 23:40:34', 'chunk_idx': 2, 'author': '', 'upload_date': '2025-12-04 13:01:16', 'file_ext': '.txt', 'file_hash': '85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b37210fc6e72ce7bfaa496f', 'title': 'demo_textfile.txt', 'page_lengths': '(8149,)', 'creation_date': '2025-11-29 23:39:54', 'source_id': 'b620ba0a-f2d0-5893-8fb0-f5611726f076'}]], 'distances': [[0.8519288301467896, 0.8687845468521118]]}
found 2 similar documents

   distance                                    id                                           document  N_chunks                  fullpath file_ext                             source_id         upload_date                                          file_hash page_lengths              title  chunk_idx       source_type author   modification_date           basename       creation_date
0  0.851929  2443d291-d7bc-5b92-a554-04af388319a1  He has constrained our fellow Citizens taken C...         6  .\data\demo_textfile.txt     .txt  b620ba0a-f2d0-5893-8fb0-f5611726f076 2025-12-04 13:01:16  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...     [8148.0]  demo_textfile.txt          4  chunked document        2025-11-29 23:40:34  demo_textfile.txt 2025-11-29 23:39:54
1  0.868785  6e75dfa6-61ce-5d73-9f0b-97e593b36e70  He has forbidden his Governors to pass Laws of...         6  .\data\demo_textfile.txt     .txt  b620ba0a-f2d0-5893-8fb0-f5611726f076 2025-12-04 13:01:16  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...     [8148.0]  demo_textfile.txt          2  chunked document        2025-11-29 23:40:34  demo_textfile.txt 2025-11-29 23:39:54

In [10]:
query ="how do I install matlab"
df_results = VD.search(query, k = 2)
df_results

{'ids': [['84d1843d-1bd1-53b8-ae55-2c2c939cdb37', '278661f7-8e8d-5a6b-b0e9-3a795d3c1d75']], 'embeddings': None, 'documents': [['Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters \n \n \n \n \n \n \n \n\nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nQuestions: \n1) Your task is to design a controller for the system.  Find the controller file with function  \nfunction F = shroff_controller(y, vy, ytop, ybot) \n \n% Goal - use the input variables to calculate a desired output force F. \n  \n% ytop:  a 1 x 21 vector with positions of the top wall.  ytop(21) is the \nfurthest from the ship. \n% ybot:  a 1 x 21 vector with positions of the bottom wall.  ybot(21) is the \nfurthest from the ship. \n% y: Current position of the ship \n% vy: Current velocity of the ship \n% F: Output force to apply in the vertical direction (can be -1 <= F <= 1, \ncode will enforce this) \n \nRead and understand all of the inputs and output of the function.   \n \n2) In words, describe how you would avoid hitting walls of the cave.  Hint:  You could say \nsomething like if you get within x units of either wall, set F to push the ship the other way.  \nAn alternative scheme would be to try to stay in the middle of the path.   \n3) Convert your scheme to mathematical equations.  Remember, you can only work with the \ninput values in the function F = yourname_controller(ytop, ybot, y, vy).  Add \ncode to the function representing these equations.  Make sure to rename the .m file with \nyour new function name yourname_controller. \n4) Run the code with your controller.  How well did you do?  Describe your process for \nsystematically tuning the controller (for example, how did you use educated guesses to \ntune the strength of forces?).  Try a different control scheme if needed. \n5) Run levels [1, 2, 4, 8, 16, …., 2048] by changing M.levels.  Record the impact time t \nfor each level and take the average.  Report the individual times on the class spreadsheet \n(https://docs.google.com/spreadsheets/d/185q_onHT4oSUj3FxN-12PGQVs_D_wGWYxbHLlN0gWTM/edit?usp=sharing). \n6) In a few sentences describe important factors that were not taken into account in this \nsimulation.  Hint: think about sensor noise, delay in changing the thrust, etc.  Could your \ncontroller be used on different ships?  If the mass of a ship was twice as much, or the cave \nwall shapes were very different (more jagged for example), do you think your controller \nwould have to be adjusted? \n7) Submit answers to these questions as well as controller code on Canvas. \nOptional Upload: \nUpload your controller file here.  We will demo and discuss some of these after the assignment \nis due. \nhttps://forms.gle/pNfxWdQJNpRe6MuE6 \n \n \nOptional Bonus: \nAdd a loop in the code to quickly test your controller on levels [1, 2, 4, 8, …, 2048].  Save the \ntimes in a vector, and take the average.  Try to optimize the average time until collision by \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 3 \nchanging parameter values in your code.  Show that you have found a local minima by \ndemonstrating that by either increasing or decreasing one of the parameters, the average time \ndecreases. \n \n']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'file_ext': '.pdf', 'file_hash': 'd235a1898843e3a439eabc58b387565f659900d564460438304b195186542fe6', 'source_type': 'chunked document', 'title': 'HW 1 - Cave Flyer.pdf', 'author': 'Sameer Shroff', 'id': '84d1843d-1bd1-53b8-ae55-2c2c939cdb37', 'chunk_idx': 0, 'basename': 'HW 1 - Cave Flyer.pdf', 'page_lengths': '(974, 2735, 291)', 'N_chunks': 3, 'source_id': '278661f7-8e8d-5a6b-b0e9-3a795d3c1d75', 'fullpath': '.\\data\\HW 1 - Cave Flyer.pdf', 'modification_date': '2024-08-25 16:26:44', 'creation_date': '2025-11-26 11:27:12', 'upload_date': '2025-12-04 13:01:16'}, {'source_type': 'full document', 'fullpath': '.\\data\\HW 1 - Cave Flyer.pdf', 'N_chunks': 0, 'file_ext': '.pdf', 'source_id': '278661f7-8e8d-5a6b-b0e9-3a795d3c1d75', 'file_hash': 'd235a1898843e3a439eabc58b387565f659900d564460438304b195186542fe6', 'upload_date': '2025-12-04 13:01:16', 'chunk_idx': -1, 'modification_date': '2024-08-25 16:26:44', 'page_lengths': '(974, 2735, 291)', 'id': '278661f7-8e8d-5a6b-b0e9-3a795d3c1d75', 'author': 'Sameer Shroff', 'title': 'HW 1 - Cave Flyer.pdf', 'creation_date': '2025-11-26 11:27:12', 'basename': 'HW 1 - Cave Flyer.pdf'}]], 'distances': [[0.46769022941589355, 0.4774061441421509]]}
found 2 similar documents

   distance                                    id                                           document file_ext                                          file_hash       source_type                  title         author  chunk_idx               basename            page_lengths  N_chunks                             source_id                      fullpath   modification_date       creation_date         upload_date
0  0.467690  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co...     .pdf  d235a1898843e3a439eabc58b387565f659900d5644604...  chunked document  HW 1 - Cave Flyer.pdf  Sameer Shroff          0  HW 1 - Cave Flyer.pdf  [974.0, 2736.0, 291.0]         3  278661f7-8e8d-5a6b-b0e9-3a795d3c1d75  .\data\HW 1 - Cave Flyer.pdf 2024-08-25 16:26:44 2025-11-26 11:27:12 2025-12-04 13:01:16
1  0.477406  278661f7-8e8d-5a6b-b0e9-3a795d3c1d75  Carnegie Mellon University 24-451: Feedback Co...     .pdf  d235a1898843e3a439eabc58b387565f659900d5644604...     full document  HW 1 - Cave Flyer.pdf  Sameer Shroff         -1  HW 1 - Cave Flyer.pdf  [974.0, 2736.0, 291.0]         0  278661f7-8e8d-5a6b-b0e9-3a795d3c1d75  .\data\HW 1 - Cave Flyer.pdf 2024-08-25 16:26:44 2025-11-26 11:27:12 2025-12-04 13:01:16

In [11]:
query ="what options do I have to install matlab in detail"
response = VD.query(query, k = 10)
print(response.content)

{'ids': [['84d1843d-1bd1-53b8-ae55-2c2c939cdb37', '278661f7-8e8d-5a6b-b0e9-3a795d3c1d75', '34d76a86-10c7-52c4-b9fa-a71985820b17', '7fc073a6-6e1e-56c1-8e0e-9cadc79ce416', '66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce', 'c6aeca0f-6ea7-585e-b995-1cf9b71baef3', '31d1eafa-c729-54c6-ac3d-5255371c96e7', '6da8d02a-6ffa-5410-8915-cb4992b2a3e0', 'ad157204-5bfd-5c8f-b7e0-8e1091b814ab', 'a9b7e972-fbf0-5ff5-af3c-19fba77410f6']], 'embeddings': None, 'documents': [['Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters \n \n \n \n \n \n \n \n\nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nQuestions: \n1) Your task is to design a controller for the system.  Find the controller file with function  \nfunction F = shroff_controller(y, vy, ytop, ybot) \n \n% Goal - use the input variables to calculate a desired output force F. \n  \n% ytop:  a 1 x 21 vector with positions of the top wall.  ytop(21) is the \nfurthest from the ship. \n% ybot:  a 1 x 21 vector with positions of the bottom wall.  ybot(21) is the \nfurthest from the ship. \n% y: Current position of the ship \n% vy: Current velocity of the ship \n% F: Output force to apply in the vertical direction (can be -1 <= F <= 1, \ncode will enforce this) \n \nRead and understand all of the inputs and output of the function.   \n \n2) In words, describe how you would avoid hitting walls of the cave.  Hint:  You could say \nsomething like if you get within x units of either wall, set F to push the ship the other way.  \nAn alternative scheme would be to try to stay in the middle of the path.   \n3) Convert your scheme to mathematical equations.  Remember, you can only work with the \ninput values in the function F = yourname_controller(ytop, ybot, y, vy).  Add \ncode to the function representing these equations.  Make sure to rename the .m file with \nyour new function name yourname_controller. \n4) Run the code with your controller.  How well did you do?  Describe your process for \nsystematically tuning the controller (for example, how did you use educated guesses to \ntune the strength of forces?).  Try a different control scheme if needed. \n5) Run levels [1, 2, 4, 8, 16, …., 2048] by changing M.levels.  Record the impact time t \nfor each level and take the average.  Report the individual times on the class spreadsheet \n(https://docs.google.com/spreadsheets/d/185q_onHT4oSUj3FxN-12PGQVs_D_wGWYxbHLlN0gWTM/edit?usp=sharing). \n6) In a few sentences describe important factors that were not taken into account in this \nsimulation.  Hint: think about sensor noise, delay in changing the thrust, etc.  Could your \ncontroller be used on different ships?  If the mass of a ship was twice as much, or the cave \nwall shapes were very different (more jagged for example), do you think your controller \nwould have to be adjusted? \n7) Submit answers to these questions as well as controller code on Canvas. \nOptional Upload: \nUpload your controller file here.  We will demo and discuss some of these after the assignment \nis due. \nhttps://forms.gle/pNfxWdQJNpRe6MuE6 \n \n \nOptional Bonus: \nAdd a loop in the code to quickly test your controller on levels [1, 2, 4, 8, …, 2048].  Save the \ntimes in a vector, and take the average.  Try to optimize the average time until collision by \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 3 \nchanging parameter values in your code.  Show that you have found a local minima by \ndemonstrating that by either increasing or decreasing one of the parameters, the average time \ndecreases. \n \n', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 4 \n \nIf optimizing programmatically, it is much easier using Matlab transfer functions with \nstepinfo() rather than using Simulink.   \n \nMy optimal solution has a rise time of 0.1399 seconds.  Can you beat it? \n \n \n  \n0 0.2 0.4 0.6 0.8 1 1.2 1.4 1.6 1.8 2\n0\n5\n10\n15\n20\n25\n30\n35 Current due to 6*u(t) input', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 5 \n \nIn this homework, you will revisit questions on Exam 1 and make use of Matlab and Simulink to \nanalyze the systems in more detail.  \n \nQuestion 1 \na) Recreate the system in Matlab or Simulink. \nb) For various positive values of k, show the effect of a unit step disturbance by plotting \nthe system output vs. time (ideally all on the same graph with a legend).    \nc) Do your analytical solutions on the Exam (for steady-state value, time constant) match \nwhat you see in the simulations?  \n \nQuestion 2 \na. Recreate the model shown in Question 2 in Simulink.   \nb. On the plot displayed on the scope, label the system specifications listed in the bullet \npoints. \nNote: If you want “nicer” plots, you can use the XY Graph feature, or send both t and y \nout to the workspace (under “Sinks”) and use the Matlab plot(t,y) command.  For a \nmass-spring-damper system with no feedback, this would look something like this: \n \nc. Calculate the final value of y analytically if the input to the system is a step of \nmagnitude 𝑘1 (𝑓(𝑡) = 𝑘1𝜇(𝑡)).  Show that your Simulink model gives the same results \nfor a few values of 𝑘1. \nd. Show that the rise time, settling time, % overshoot, and peak time are not affected by \n𝑘1 using your Simulink model.  Prove this analytically as well. \nQuestion 3 \ne. Define a transfer function 𝐺(𝑠) that has 2 imaginary poles {+2j, -2j} using G = zpk(…).  \nSee our code examples if you forgot how to do this.  Show the impulse response over a \nperiod of 10 seconds using impulse(G, 10).  Explain the response, and compare to the \nanalytical solution (calculate the period and frequency analytically and compare). \n\nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nf. Define a transfer function 𝐺(𝑠) that has 2 real poles {-1, -2}.  Determine the analytical \nresponse to an impulse.  Compare your result to impulse(G, 10).   \ng. Define a transfer function 𝐺(𝑠) that has 2 complex conjugate poles (-1±j) in the left \nhalf plane.  Move the poles to the left (𝐺2(𝑠)) and further away from the x-axis (𝐺3(𝑠)).  \nPlot the impulse response for all 3 cases on the same figure and explain the output. \nQuestion 5 \nh. Recreate the system in Simulink. \ni. Use the value of K calculated in the exam that makes the rise time less than 1 and show \nthe output on the scope.  Is it what you expected? \nj. What happens as K increases?  Show and example output and qualitatively explain the \nchanges (explain changes in rise time and overshoot). \nk. For part (b), there were several ways to estimate the value of K that results in the plot \ndisplayed.  Using the value of K you calculated on your exam, show the scope output.  \nHow close were you? \nQuestion 7 \nl. Using Matlab (not Simulink), define 𝐺1 and 𝐺2.  Use the commands impulse(), step(), \nand lsim() to recreate the 6 plots.  Review our code examples if you forget how to apply \nan arbitrary input using lsim(). \nQuestion 8 \nm. Use the functions pzmap() and pzplot() to calculate the poles and zeros of G and plot \nthem in the complex plane. \nn. Vary K from 0 to 10 (in increments of .2 or smaller).  Calculate the 2 poles of 𝐺2 for each \nvalue of K (Use a loop to make this easy). \no. Plot the poles as a function of K on the complex plane.  Label 3 regions – (1) when the \npoles are complex and on the right-half plane, (2) when the poles are complex and on \nthe left-half plane, and (3) when the poles are real (on the x-axis).  On your plot, include \nthe value of K and values for the poles that divide the regions.  Draw arrows showing \nthe direction of how the poles move for increasing K. \nHint: your plot should look something like this: \n \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 3 \n \np. Calculate the boundaries of the 3 regions analytically by considering that a polynomial \nof the form 𝑎𝑥2 +𝑏𝑥 +𝑐 = 0 has roots \n−𝑏 ±√𝑏2 −4𝑎𝑐\n2𝑎  \nand examining when 𝑏2 −4𝑎𝑐 > 0, for example. \nq. Show that as K goes to infinity, the real poles stay on the left-half plane by (i) using a \nvery large value of K in your code and (ii) proving analytically.  What are the 2 poles at \nthis limit?  \nr. Consider the region where the poles are complex conjugates on the LHP.  As K \nincreases, what happens to the damping ratio, natural frequency, and damped natural \nfrequency?  What is happening to the % overshoot, rise time, and settling time? \ns. Consider the region where the poles are real on the LHP.  What happens as K \nincreases?  Remember, there are 2 first-order poles, so there will be two time \nconstants.  Does increasing K decrease the overall settling time of the system?  \nt. Consider all regions.  What value of K gives the shortest settling time overall?  Show \nthis by plotting the system response to a unit step for this value of K and for values of K \nabove and below this value on the same plot. \n \n\n', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 5 \n \nIn this homework, you will revisit questions on Exam 1 and make use of Matlab and Simulink to \nanalyze the systems in more detail.  \n \nQuestion 1 \na) Recreate the system in Matlab or Simulink. \nb) For various positive values of k, show the effect of a unit step disturbance by plotting \nthe system output vs. time (ideally all on the same graph with a legend).    \nc) Do your analytical solutions on the Exam (for steady-state value, time constant) match \nwhat you see in the simulations?  \n \nQuestion 2 \na. Recreate the model shown in Question 2 in Simulink.   \nb. On the plot displayed on the scope, label the system specifications listed in the bullet \npoints. \nNote: If you want “nicer” plots, you can use the XY Graph feature, or send both t and y \nout to the workspace (under “Sinks”) and use the Matlab plot(t,y) command.  For a \nmass-spring-damper system with no feedback, this would look something like this: \n \nc. Calculate the final value of y analytically if the input to the system is a step of \nmagnitude 𝑘1 (𝑓(𝑡) = 𝑘1𝜇(𝑡)).  Show that your Simulink model gives the same results \nfor a few values of 𝑘1. \nd. Show that the rise time, settling time, % overshoot, and peak time are not affected by \n𝑘1 using your Simulink model.  Prove this analytically as well. \nQuestion 3 \ne. Define a transfer function 𝐺(𝑠) that has 2 imaginary poles {+2j, -2j} using G = zpk(…).  \nSee our code examples if you forgot how to do this.  Show the impulse response over a \nperiod of 10 seconds using impulse(G, 10).  Explain the response, and compare to the \nanalytical solution (calculate the period and frequency analytically and compare).', '• # 7c only.  Use Simulink.  Hint: 𝐾1 will be in the 1000-1500 range to obtain the desired \nstep overshoot, and the steady state error to 𝑟 = 5𝑡 should be around 0.3.    \n• # 10.  For part (b), you can use Matlab function routh.m found at: \nhttps://www.mathworks.com/matlabcentral/fileexchange/58-routh-m \n• # 29.  Hint: use the Matlab symbolic toolbox to make the algebra trivial. \n \nRoot-Locus Design Method (Chapter 5) \n \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nDo the following book problems .  Note that you can use the Matlab function rlocus( ) for any of \nthe problems below, but make sure you have the correct L(s) when calling rlocus(L) .  For any \nasymptote or angle calculations, consider coding in Matlab to make the calculations easier: \n1. # 3.  Plot using Matlab.  Calculate the asymptotes and label them on the plot. \n2. # 7.  Plot using Matlab.  Then, calculate the arrival angles, departure angles, and any \nasymptotes and label them on your plots.  Hint: You can use Matlab to make the \nrepetitive calculations easier. \n3. # 8(d) using Matlab.  Also specify the value of K for which the maximum damping occurs. \n4. # 9 \n5. # 13 using Matlab \n6. # 21 (you can use the routh.m function) \n \nOptional bonus: \n7. # 18.   First test the claim in Matlab for various values of z and p, then prove analytically.', 'axis). \n7. Consider a set of points that form a closed polygon in the complex plane when \nconnected in order.  For example: \nCarnegie Mellon University 24-451: Feedback Control Systems\n Instructor: Dr. Sameer Shroff \n 2 \n1 + 0𝑗, 2 + 0𝑗, 2 + 1𝑗, 1 + 1𝑗, 1 + 0𝑗 \nYou wish to rotate these points by 30° about the origin in the complex plane.  What \ncomplex number should you multiply by?  Show this works using Matlab. \n \nNewton’s Method \nNewton’s method can be used to find the roots of a function.  One starts with an initial guess \n𝑥0.  The guess is updated as  \n𝑥𝑛+1 = 𝑥𝑛 − 𝑓(𝑥𝑛)\n𝑓′(𝑥𝑛) \n \n8. Consider the polynomial  \n𝑓(𝑥) = 𝑥3 + 1 \na. Use the Matlab command roots() to find the roots of the polynomial (𝑝1, 𝑝2, 𝑝3). \nb. Analytically compute 𝑓′(𝑥). \nc. Pick a starting value 𝑥0,1 from the complex plane and show it converges to root  \n𝑝1 using Newton’s method.  Similarly show different starting values 𝑥0,2 and 𝑥0,3 \nconverge to 𝑝2 and 𝑝3, respectively.  Plot each sequence of values 𝑥𝑛,𝑖 in the \ncomplex plane and show they terminate at 𝑝𝑖. \nOptional Bonus Problems:  \n9. You wish to first scale the shape by factor 𝛼 and then rotate it about an arbitrary point \n𝑐1 + 𝑐2𝑗 by 𝜃 degrees.  Describe your methodology (equations) for doing this using \ncomplex algebra, and show it works in Matlab for 𝛼 = 2, 𝑐1 = 3, 𝑐2 = 1, 𝜃 = 30°. \n \nExample output: \n \n \n10. Consider the polynomial  \n𝑓(𝑥) = 𝑥3 + 1 \nAnd a square in the complex plane 𝑆 = 𝑎 + 𝑏𝑗, where −1 ≤ 𝑎 ≤ 1 and −1 ≤ 𝑏 ≤ 1 \na. Using Netwon’s method, map regions of 𝑆 to the root they terminate at.  Hint: \ncreate a mesh of points in 𝑆 that represent starting points, and run Newton’s \n1 1.5 2 2.5 3 3.5 4\n0\n0.5\n1\n1.5\n2\nCarnegie Mellon University 24-451: Feedback Control Systems\n Instructor: Dr. Sameer Shroff \n 3 \nmethod on each of these points.  You may want to vectorize the calculations.  \nThere may be some points that never converge, which is a known limitation to', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 3 \n \nh) Recreate the system in Simulink.  Note: use the PID controller block instead of trying to \ncreate a PID controller manually if you plan on using derivative control (the du/dt block \ndoes not handle step inputs very well).   \ni) Start with a proportional controller 𝐶(𝑠) = 𝑘𝑃.  Is it possible to meet all of the \nrequirements?  If so, provide output plots at that value of 𝑘𝑃.  If not, prove this using \nroot locus or another method. \nj) Consider a PI controller (𝐶(𝑠) =\n𝑘𝐼\n𝑠 + 𝑘𝑃).  Select controller values of 𝑘𝑃 and 𝑘𝐼 that \nsatisfy all of the requirements.  Prove the requirements are satisfied either analytically \nor through simulation.  Explain your methodology. \nk) Fill out the table below: \nRequirement type Requirement Actual \nP \n𝑘𝑃 = \n \nPI \n𝑘𝑃 = \n𝑘𝐼 = \nPID \n𝑘𝑃 = \n𝑘𝐼 = \n𝑘𝐷 = \nsteady state error for step ess = 0    \n1% settling time to a step ts,1% < 2.8 s    \ncurrent maximum for a step input \nof 6 deg/s (not unit step) \nImax < 30 A    \n% overshoot Mp due to a step Mp < 40%    \nrise time tr (no requirement)    \n* highlighted cells are for the bonus problem \nl) Optional bonus:  Consider a PID controller, where 𝑘𝐷 may be negative (which would \nmean removing damping from the system).  Select PID coefficients such that all of the \nrequirements are met while optimizing for the fastest rise time.  Explain your \nmethodology.   \nNote: use the PID controller block instead of trying to create a PID controller manually if \nyou plan on using derivative control (the du/dt block does not handle step inputs very \nwell).  In this block, make the filter coefficient very large to approximate ideal \nderivatives. \n \n \nMake sure you change the simulation max step time and stop time to appropriate \nvalues to get good accuracy.', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 7 \nDesign Challenges \n \nThe following homework consists of 4 design challenges of varying levels of difficulty.  I suggest \ncompleting all required steps before attempting any optional bonus problems. \n \n \nProblem 1 \nConsider the following block diagram: \n \n \na) Determine the loop gain of the system. \nb) Determine the system type. \nc) Determine the steady state error due to step, ramp, and parabolic inputs as functions of \n𝐴. \nd) Consider a unit step input.  How does the % overshoot vary as a function of 𝐴?  Use a \nroot locus plot to aid your explanation (you can use rlocus in Matlab – remember the \nequation for the poles must be in root locus form).  Also show the simulation output at \n2 values of 𝐴.   \ne) For what values of 𝐴 is the system stable?  Use a root locus plot or Routh array to aid \nyour explanation (you can use rlocus() or routh() in Matlab).   \n \nProblem 2 \nThe loop gain in a servomotor control system is given by \n𝐿(𝑠) = 𝐾\n𝑠(𝑠 + 𝛼) \nf) Assuming unity feedback, pick values of 𝐾 and 𝛼 such that  \n(i) the steady state error due to a ramp 𝑒𝑠𝑠,𝑟𝑎𝑚𝑝 = 0.04. \n(ii) the % overshoot due to a unit step is 16.3%. \ng) Simulate the system with step and ramp inputs and show that your parameters meet \nthe specifications. \n \n  \n\nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nProblem 3 – Electromechanical design \nRead Section 4.3 of the book for background information on PID control and tuning.  Pay \nparticular attention to Section 4.3.6 “Ziegler-Nichols Tuning” for one way of how to select PID \ncoefficients.  Although these coefficients will need to be revised based on the specifications you \nwant to meet, they usually will be good initial guesses.  Note that for some systems (hint: \npossibly in thi

In [12]:
import source.cluster as cluster_analysis
importlib.reload(cluster_analysis)

CA = cluster_analysis.ClusterAnalyis(VD)


CA.calculate_pca()
CA.perform_kmeans_clustering(n_clusters=5)


df = VD.get(keep_cols = ['id', 'kmeans_cluster_idx', 'pca_embedding'])

embeddings matrix is (43, 384)
pca matrix is (43, 43)
updated metadata for 43 records for the following keys: {'pca_embedding'}
embeddings matrix is (43, 43)
performed kmeans clustering with 5 clusters
kmeans_cluster_idx
4     7
3     7
2     3
1    24
0     2
Name: count, dtype: int64
updated metadata for 43 records for the following keys: {'kmeans_cluster_idx'}

In [13]:
df = VD.get(keep_cols = ['id', 'kmeans_cluster_idx', 'pca_embedding'])
df

                                      id  kmeans_cluster_idx                                      pca_embedding
0   b620ba0a-f2d0-5893-8fb0-f5611726f076                   4  [-0.962, -0.08295, 0.0772, 0.07245, 0.06036, 0...
1   d00a351a-96b3-560b-8b31-f7dab9abc247                   4  [-0.892, -0.0319, 0.003881, 0.09717, 0.09216, ...
2   ac16fb33-1007-5f21-badf-51326739eae1                   4  [-0.8535, -0.02974, 0.0956, 0.03983, -0.0127, ...
3   6e75dfa6-61ce-5d73-9f0b-97e593b36e70                   4  [-0.773, -0.07635, 0.1388, -0.1243, -0.0474, -...
4   7f7ee21b-13c6-5bd6-927b-45ae4a2d217a                   4  [-0.828, -0.04965, -0.06226, -0.08014, -0.0589...
5   2443d291-d7bc-5b92-a554-04af388319a1                   4  [-0.8, -0.02301, 0.11774, -0.11304, -0.04816, ...
6   6387ac27-fb24-5a6b-9830-4c22a1923477                   4  [-0.9175, -0.0663, 0.0829, 0.0478, -0.01009, 0...
7   278661f7-8e8d-5a6b-b0e9-3a795d3c1d75                   3  [0.1947, -0.05695, -0.4592, -0.014175, 0.02351...
8   84d1843d-1bd1-53b8-ae55-2c2c939cdb37                   3  [0.1943, -0.04697, -0.465, -0.022, 0.03333, -0...
9   a6a533b9-7542-5de9-997e-a8bf62a2567d                   3  [0.02481, 0.1566, -0.502, -0.1741, 0.09106, -0...
10  8db318ca-8016-52e1-895a-b94b73bf5866                   3  [-0.0343, 0.2434, -0.4521, -0.1904, 0.2339, 0....
11  6b05026a-6866-5d10-9f05-55d96590efd0                   2  [0.1531, 0.11163, 0.00729, 0.4543, -0.3098, -0...
12  b5d3bc77-d338-5180-965f-5f40c72baed2                   2  [0.1531, 0.11163, 0.00729, 0.4543, -0.3098, -0...
13  31d1eafa-c729-54c6-ac3d-5255371c96e7                   2  [0.07367, 0.293, -0.0403, 0.5645, -0.15, -0.04...
14  af0e56d4-5e39-52fb-9a06-f6bb1c058b49                   1  [0.01563, 0.4333, 0.02293, 0.3228, 0.1525, 0.1...
15  7b199add-cc2e-531b-8674-4feb26904f3d                   3  [0.06433, -0.549, -0.3894, 0.1384, -0.1084, -0...
16  2cd378ca-b422-51cb-9571-1bd060000b9b                   3  [0.06433, -0.549, -0.3894, 0.1384, -0.1084, -0...
17  a15a1017-2f3c-53dd-b46b-b1e946be0626                   1  [0.1123, -0.1678, 0.02959, -0.0622, -0.2325, 0...
18  f2b9c5c1-9186-5c6f-a312-18e0acb3184c                   1  [0.1259, -0.1632, 0.1486, -0.2356, -0.078, 0.2...
19  2f69e529-3bc2-5a92-874b-b6721ac6adf4                   1  [0.1749, 0.09576, -0.01695, -0.1202, -0.2021, ...
20  02ef51c4-8f87-552e-8832-f72ed1df50ef                   0  [-0.062, 0.4932, -0.1746, 0.03662, 0.1594, 0.2...
21  b48ccef8-b823-580c-b6a0-bda17e9a9390                   1  [0.1964, 0.01617, -0.004547, -0.08093, -0.3699...
22  07d9494a-ea63-53ef-8cb4-07742beb9abb                   1  [0.1964, 0.01617, -0.004547, -0.08093, -0.3699...
23  62b4072a-1df9-55d9-a9a3-457666485e0c                   0  [0.1393, 0.1794, 0.1636, -0.254, -0.1624, 0.17...
24  7fc073a6-6e1e-56c1-8e0e-9cadc79ce416                   1  [0.2798, -0.1648, 0.1439, -0.2502, -0.0853, 0....
25  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce                   1  [0.2798, -0.1648, 0.1439, -0.2502, -0.0853, 0....
26  fd404feb-816b-5840-b735-a1266097fa05                   1  [0.2537, -0.0254, 0.2225, -0.1162, -0.0494, -0...
27  a8aa1388-28e7-5e69-9266-2b9048abfce8                   1  [0.218, 0.1351, 0.2942, 0.1063, 0.0901, -0.071...
28  566ede87-b00d-52ae-9f8d-d8ee8b019ab8                   1  [0.285, -0.10144, 0.1984, -0.0048, -0.03607, 0...
29  633cf765-5101-537d-944a-50becd881f81                   1  [0.285, -0.10144, 0.1984, -0.0048, -0.03607, 0...
30  c6aeca0f-6ea7-585e-b995-1cf9b71baef3                   1  [0.3098, 0.172, 0.03516, -0.00881, 0.0541, -0....
31  ad157204-5bfd-5c8f-b7e0-8e1091b814ab                   1  [0.3408, -0.01109, 0.0865, 0.0573, 0.0744, -0....
32  a9b7e972-fbf0-5ff5-af3c-19fba77410f6                   1  [0.3408, -0.01109, 0.0865, 0.0573, 0.0744, -0....
33  83b8a84b-a11d-5cb1-b2d7-758e1d86b895                   1  [0.07806, -0.02826, -0.01633, 0.10126, 0.3757,...
34  6da8d02a-6ffa-5410-8915-cb4992b2a3e0                   1  [0.271, -0.08514, 0.0409, -0.0863, 0.12396, -0...
35  34d76a86-10c7-52c4-b9fa-a71985820b17                   1  [0.193, 0.0899, 0.003956, -0.2273, -0.0006294,...
36  27094245-284d-571e-8e0d-4f4a1ebb03f6                   3  [-0.01967, 0.2168, -0.002209, -0.1907, -0.0112...
37  4b983cb4-395e-5079-a6f3-89783cc878ac                   1  [0.2157, 0.02861, 0.0706, -0.2175, 0.12494, -0...
38  c1c38fd3-bf54-54af-b292-b4bdda4fb016                   1  [-0.0177, 0.5215, -0.0502, -0.2761, -0.04486, ...
39  7cf34e95-db98-511b-ac82-8e0595b014d9                   1  [0.2664, -0.1344, 0.2235, 0.1613, 0.226, 0.010...
40  c6566691-5068-5848-a341-39c0910c40bc                   1  [0.2664, -0.1344, 0.2235, 0.1613, 0.226, 0.010...
41  70354a5d-490e-59e0-8973-ed82cf0995a8                   1  [0.1967, -0.2295, 0.08075, 0.0869, 0.3557, 0.0...
42  9e5afc2a-3f98-5a8b-b375-24fa92c0cd58                   1  [0.1967, -0.2295, 0.08075, 0.0869, 0.3557, 0.0...

In [14]:
id = parsers.generate_document_uuid_from_path(files[0])
r = VD.collection.get(ids = id, include = [])
id_exists = len(r['ids'])>0

print(id_exists)

True

In [15]:
df = VD.get(keep_cols=['pca_embedding'])
df

                                        pca_embedding
0   [-0.962, -0.08295, 0.0772, 0.07245, 0.06036, 0...
1   [-0.892, -0.0319, 0.003881, 0.09717, 0.09216, ...
2   [-0.8535, -0.02974, 0.0956, 0.03983, -0.0127, ...
3   [-0.773, -0.07635, 0.1388, -0.1243, -0.0474, -...
4   [-0.828, -0.04965, -0.06226, -0.08014, -0.0589...
5   [-0.8, -0.02301, 0.11774, -0.11304, -0.04816, ...
6   [-0.9175, -0.0663, 0.0829, 0.0478, -0.01009, 0...
7   [0.1947, -0.05695, -0.4592, -0.014175, 0.02351...
8   [0.1943, -0.04697, -0.465, -0.022, 0.03333, -0...
9   [0.02481, 0.1566, -0.502, -0.1741, 0.09106, -0...
10  [-0.0343, 0.2434, -0.4521, -0.1904, 0.2339, 0....
11  [0.1531, 0.11163, 0.00729, 0.4543, -0.3098, -0...
12  [0.1531, 0.11163, 0.00729, 0.4543, -0.3098, -0...
13  [0.07367, 0.293, -0.0403, 0.5645, -0.15, -0.04...
14  [0.01563, 0.4333, 0.02293, 0.3228, 0.1525, 0.1...
15  [0.06433, -0.549, -0.3894, 0.1384, -0.1084, -0...
16  [0.06433, -0.549, -0.3894, 0.1384, -0.1084, -0...
17  [0.1123, -0.1678, 0.02959, -0.0622, -0.2325, 0...
18  [0.1259, -0.1632, 0.1486, -0.2356, -0.078, 0.2...
19  [0.1749, 0.09576, -0.01695, -0.1202, -0.2021, ...
20  [-0.062, 0.4932, -0.1746, 0.03662, 0.1594, 0.2...
21  [0.1964, 0.01617, -0.004547, -0.08093, -0.3699...
22  [0.1964, 0.01617, -0.004547, -0.08093, -0.3699...
23  [0.1393, 0.1794, 0.1636, -0.254, -0.1624, 0.17...
24  [0.2798, -0.1648, 0.1439, -0.2502, -0.0853, 0....
25  [0.2798, -0.1648, 0.1439, -0.2502, -0.0853, 0....
26  [0.2537, -0.0254, 0.2225, -0.1162, -0.0494, -0...
27  [0.218, 0.1351, 0.2942, 0.1063, 0.0901, -0.071...
28  [0.285, -0.10144, 0.1984, -0.0048, -0.03607, 0...
29  [0.285, -0.10144, 0.1984, -0.0048, -0.03607, 0...
30  [0.3098, 0.172, 0.03516, -0.00881, 0.0541, -0....
31  [0.3408, -0.01109, 0.0865, 0.0573, 0.0744, -0....
32  [0.3408, -0.01109, 0.0865, 0.0573, 0.0744, -0....
33  [0.07806, -0.02826, -0.01633, 0.10126, 0.3757,...
34  [0.271, -0.08514, 0.0409, -0.0863, 0.12396, -0...
35  [0.193, 0.0899, 0.003956, -0.2273, -0.0006294,...
36  [-0.01967, 0.2168, -0.002209, -0.1907, -0.0112...
37  [0.2157, 0.02861, 0.0706, -0.2175, 0.12494, -0...
38  [-0.0177, 0.5215, -0.0502, -0.2761, -0.04486, ...
39  [0.2664, -0.1344, 0.2235, 0.1613, 0.226, 0.010...
40  [0.2664, -0.1344, 0.2235, 0.1613, 0.226, 0.010...
41  [0.1967, -0.2295, 0.08075, 0.0869, 0.3557, 0.0...
42  [0.1967, -0.2295, 0.08075, 0.0869, 0.3557, 0.0...