In [1]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import source.parsers as parsers
import source.database as database
import importlib
import os
import glob
importlib.reload(parsers)
importlib.reload(database)
import pandas as pd

In [2]:
device = "cuda"
database_folder = "./database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

VD = database.VectorDatabase(device, database_folder)
VD.info()
VD.clear_collections()
VD.create_collection()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records
deleted data in Collection(name=documents)

`torch_dtype` is deprecated! Use `dtype` instead!

created collection: Collection(name=documents) with 0 documents

In [3]:
glob_pattern = os.path.join('.', 'data', '*')
files = glob.glob(glob_pattern)

for file in files:
   VD.add_documents(file)

.\data\demo_textfile.txt
- added 1 documents, 6 chunks
.\data\HW 1 - Cave Flyer.pdf
- added 1 documents, 3 chunks
.\data\HW 2 - Complex Numbers.pdf
- added 1 documents, 3 chunks
.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
- added 1 documents, 5 chunks
.\data\HW 4 - Linearization and Dynamic Response.pdf
- added 1 documents, 2 chunks
.\data\HW 5 - Exam 1 in Matlab.pdf
- added 1 documents, 3 chunks
.\data\HW 6 - Routh Array and Root Locus.pdf
- added 1 documents, 2 chunks
.\data\HW 7 - Design Challenges.pdf
- added 1 documents, 7 chunks
.\data\HW 8 - Nyquist Stability.pdf
- added 1 documents, 1 chunks
.\data\HW 9 - Stability Margins and Compensation.pdf
- added 1 documents, 1 chunks

In [4]:
VD.info()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records

In [5]:
results = VD.collection.query(query_texts='test', include = ['embeddings'])
df_results = database._results_to_df(results, keep_cols = ['id', 'document', 'embedding'], document_length_limit= 10)
df_results

                                     id                                          embedding
0  6387ac27-fb24-5a6b-9830-4c22a1923477  [-0.05762236937880516, -0.027064252644777298, ...
1  6e75dfa6-61ce-5d73-9f0b-97e593b36e70  [0.005074928980320692, 0.01837628148496151, 0....
2  7f7ee21b-13c6-5bd6-927b-45ae4a2d217a  [-0.023129954934120178, 0.050913888961076736, ...
3  d00a351a-96b3-560b-8b31-f7dab9abc247  [-0.0233257208019495, 0.02008930593729019, 0.0...
4  fd404feb-816b-5840-b735-a1266097fa05  [-0.070555180311203, -0.02415478229522705, -0....
5  a15a1017-2f3c-53dd-b46b-b1e946be0626  [-0.07547421008348465, -0.05921144783496857, -...
6  31d1eafa-c729-54c6-ac3d-5255371c96e7  [-0.1016826406121254, -0.03408649191260338, -0...
7  a6a533b9-7542-5de9-997e-a8bf62a2567d  [0.0683976411819458, 0.051735371351242065, -0....
8  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a  [-0.07416589558124542, 0.04833682253956795, -0...
9  8db318ca-8016-52e1-895a-b94b73bf5866  [-0.018426241353154182, -0.0294819176197052, 0...

In [6]:
query ="how do I install matlab"
df_results = VD.search(query, k = 10)
df_results

found 10 similar documents

   distance                                    id                                           document         author         upload_date       source_type                                              title                             source_id pca                                           basename                               page_lengths   modification_date  N_chunks                                           fullpath file_ext       creation_date                                          file_hash  chunk_idx tfidf
0  0.467690  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:39  chunked document                              HW 1 - Cave Flyer.pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  ()                              HW 1 - Cave Flyer.pdf                           (974, 2735, 291) 2024-08-25 16:26:44         3                       .\data\HW 1 - Cave Flyer.pdf     .pdf 2025-11-26 11:27:12  d235a1898843e3a439eabc58b387565f659900d5644604...          0    ()
1  0.477406  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:39     full document                              HW 1 - Cave Flyer.pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  ()                              HW 1 - Cave Flyer.pdf                           (974, 2735, 291) 2024-08-25 16:26:44         0                       .\data\HW 1 - Cave Flyer.pdf     .pdf 2025-11-26 11:27:12  d235a1898843e3a439eabc58b387565f659900d5644604...         -1    ()
2  0.712826  34d76a86-10c7-52c4-b9fa-a71985820b17  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:41  chunked document                       HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  ()                       HW 7 - Design Challenges.pdf  (1352, 1462, 1842, 401, 1634, 1157, 1138) 2022-10-23 12:31:27         7                .\data\HW 7 - Design Challenges.pdf     .pdf 2025-11-26 11:27:12  abec6a608c256b197114106e8843696d0ea0cf2fff8710...          3    ()
3  0.733397  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  • # 7c only.  Use Simulink.  Hint: 𝐾1 will be ...  Sameer Shroff 2025-12-01 14:18:40  chunked document              HW 6 - Routh Array and Root Locus.pdf  2c2a9853-3781-5770-8e9f-c5726b15291d  ()              HW 6 - Routh Array and Root Locus.pdf                                (2191, 957) 2023-10-04 17:23:37         2       .\data\HW 6 - Routh Array and Root Locus.pdf     .pdf 2025-11-26 11:27:12  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...          1    ()
4  0.748378  31d1eafa-c729-54c6-ac3d-5255371c96e7  axis). \n7. Consider a set of points that form...  Sameer Shroff 2025-12-01 14:18:39  chunked document                         HW 2 - Complex Numbers.pdf  41fc35d3-e8dd-5ea0-9c4f-fea6a7d36787  ()                         HW 2 - Complex Numbers.pdf                          (1937, 1550, 600) 2024-08-27 20:24:40         3                  .\data\HW 2 - Complex Numbers.pdf     .pdf 2025-11-26 11:27:12  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...          1    ()
5  0.754025  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:41     full document                       HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  ()                       HW 7 - Design Challenges.pdf  (1352, 1462, 1842, 401, 1634, 1157, 1138) 2022-10-23 12:31:27         0                .\data\HW 7 - Design Challenges.pdf     .pdf 2025-11-26 11:27:12  abec6a608c256b197114106e8843696d0ea0cf2fff8710...         -1    ()
6  0.754025  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:41  chunked document                       HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  ()                       HW 7 - Design Challenges.pdf  (1352, 1462, 1842, 401, 1634, 1157, 1138) 2022-10-23 12:31:27         7                .\data\HW 7 - Design Challenges.pdf     .pdf 2025-11-26 11:27:12  abec6a608c256b197114106e8843696d0ea0cf2fff8710...          0    ()
7  0.755816  2f69e529-3bc2-5a92-874b-b6721ac6adf4  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:39  chunked document  HW 3 - Laplace Transforms and Intro to Control...  dc14db90-fbd5-55d7-bf3e-dbca0e531fe1  ()  HW 3 - Laplace Transforms and Intro to Control...                    (2363, 1621, 1323, 682) 2022-09-07 20:37:59         5  .\data\HW 3 - Laplace Transforms and Intro to ...     .pdf 2025-11-26 11:27:12  b907d592332785225f53963d7e64d3379ba273adfb78ba...          3    ()
8  0.757619  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:40  chunked document                        HW 5 - Exam 1 in Matlab.pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334  ()                        HW 5 - Exam 1 in Matlab.pdf                         (1749, 2024, 1216) 2024-09-25 17:53:25         3                 .\data\HW 5 - Exam 1 in Matlab.pdf     .pdf 2025-11-26 11:27:12  910573961d42ea022be07ca314325b4400a963f89e1795...          0    ()
9  0.757619  8bf3b706-bed9-57bb-b088-6a6ca5278334  Carnegie Mellon University 24-451: Feedback Co...  Sameer Shroff 2025-12-01 14:18:40     full document                        HW 5 - Exam 1 in Matlab.pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334  ()                        HW 5 - Exam 1 in Matlab.pdf                         (1749, 2024, 1216) 2024-09-25 17:53:25         0                 .\data\HW 5 - Exam 1 in Matlab.pdf     .pdf 2025-11-26 11:27:12  910573961d42ea022be07ca314325b4400a963f89e1795...         -1    ()

In [7]:
query ="what options do I have to install matlab in detail"
response = VD.query(query, k = 10)
print(response.content)

found 10 similar documents
You have the following options to install or run MATLAB:
*   **Download and install MATLAB locally**: You can download and install MATLAB by visiting the website: https://www.cmu.edu/computing/software/all/matlab/.
*   **Run MATLAB online through a browser**: You can access MATLAB online through a browser at: https://www.mathworks.com/products/matlab-online.html.
*   **Run MATLAB through a Virtual Andrew session**: You can run MATLAB through a Virtual Andrew session by following the instructions at: https://www.cmu.edu/computing/services/endpoint/software/managed-desktops/how-to/virtual-andrew.html.

(source: HW 1 - Cave Flyer.pdf)

In [8]:

df_results = VD.chunked_get(keep_cols = ['id', 'page_lengths'])
df_results

                                      id                               page_lengths
0   c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a                                    (8149,)
1   d00a351a-96b3-560b-8b31-f7dab9abc247                                    (8149,)
2   ac16fb33-1007-5f21-badf-51326739eae1                                    (8149,)
3   6e75dfa6-61ce-5d73-9f0b-97e593b36e70                                    (8149,)
4   7f7ee21b-13c6-5bd6-927b-45ae4a2d217a                                    (8149,)
5   2443d291-d7bc-5b92-a554-04af388319a1                                    (8149,)
6   6387ac27-fb24-5a6b-9830-4c22a1923477                                    (8149,)
7   18b8a5c1-0e02-5935-8acb-b6b32f32ae36                           (974, 2735, 291)
8   84d1843d-1bd1-53b8-ae55-2c2c939cdb37                           (974, 2735, 291)
9   a6a533b9-7542-5de9-997e-a8bf62a2567d                           (974, 2735, 291)
10  8db318ca-8016-52e1-895a-b94b73bf5866                           (974, 2735, 291)
11  41fc35d3-e8dd-5ea0-9c4f-fea6a7d36787                          (1937, 1550, 600)
12  b5d3bc77-d338-5180-965f-5f40c72baed2                          (1937, 1550, 600)
13  31d1eafa-c729-54c6-ac3d-5255371c96e7                          (1937, 1550, 600)
14  af0e56d4-5e39-52fb-9a06-f6bb1c058b49                          (1937, 1550, 600)
15  dc14db90-fbd5-55d7-bf3e-dbca0e531fe1                    (2363, 1621, 1323, 682)
16  2cd378ca-b422-51cb-9571-1bd060000b9b                    (2363, 1621, 1323, 682)
17  a15a1017-2f3c-53dd-b46b-b1e946be0626                    (2363, 1621, 1323, 682)
18  f2b9c5c1-9186-5c6f-a312-18e0acb3184c                    (2363, 1621, 1323, 682)
19  2f69e529-3bc2-5a92-874b-b6721ac6adf4                    (2363, 1621, 1323, 682)
20  02ef51c4-8f87-552e-8832-f72ed1df50ef                    (2363, 1621, 1323, 682)
21  80db1571-34fa-53aa-8a56-b39681278855                                (1457, 659)
22  07d9494a-ea63-53ef-8cb4-07742beb9abb                                (1457, 659)
23  62b4072a-1df9-55d9-a9a3-457666485e0c                                (1457, 659)
24  8bf3b706-bed9-57bb-b088-6a6ca5278334                         (1749, 2024, 1216)
25  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce                         (1749, 2024, 1216)
26  fd404feb-816b-5840-b735-a1266097fa05                         (1749, 2024, 1216)
27  a8aa1388-28e7-5e69-9266-2b9048abfce8                         (1749, 2024, 1216)
28  2c2a9853-3781-5770-8e9f-c5726b15291d                                (2191, 957)
29  633cf765-5101-537d-944a-50becd881f81                                (2191, 957)
30  c6aeca0f-6ea7-585e-b995-1cf9b71baef3                                (2191, 957)
31  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  (1352, 1462, 1842, 401, 1634, 1157, 1138)
32  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  (1352, 1462, 1842, 401, 1634, 1157, 1138)
33  83b8a84b-a11d-5cb1-b2d7-758e1d86b895  (1352, 1462, 1842, 401, 1634, 1157, 1138)
34  6da8d02a-6ffa-5410-8915-cb4992b2a3e0  (1352, 1462, 1842, 401, 1634, 1157, 1138)
35  34d76a86-10c7-52c4-b9fa-a71985820b17  (1352, 1462, 1842, 401, 1634, 1157, 1138)
36  27094245-284d-571e-8e0d-4f4a1ebb03f6  (1352, 1462, 1842, 401, 1634, 1157, 1138)
37  4b983cb4-395e-5079-a6f3-89783cc878ac  (1352, 1462, 1842, 401, 1634, 1157, 1138)
38  c1c38fd3-bf54-54af-b292-b4bdda4fb016  (1352, 1462, 1842, 401, 1634, 1157, 1138)
39  0e0c2f7c-e486-585a-ba6d-fe94b0b26e03                                    (1230,)
40  c6566691-5068-5848-a341-39c0910c40bc                                    (1230,)
41  662b39f1-3edc-5e7c-97a5-86a3af255560                                    (1682,)
42  9e5afc2a-3f98-5a8b-b375-24fa92c0cd58                                    (1682,)

In [ ]:
# labels, inertia, df_pca = DS.run_kmeans(n_clusters = 3)
# df_pca

In [ ]:
# id = DS.collection.get(limit = 1)['ids'][0]
# df = DS.search_by_id(id, k =10, where = {'source_type':'full document'})
# print(df)

In [ ]:
# import pandas as pd

# id = DS.collection.get(limit = 1)['ids'][0]
# r = DS.collection.get(id, include = ['embeddings'])
# embedding = r['embeddings']
# results = DS.collection.query(query_embeddings=embedding, include=['distances', 'metadatas', 'documents'])
# df_results= shroff_rag._results_to_df(results)[0]
# df_results = df_results.sort_values('distance')
# df_results