In [1]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import source.parsers as parsers
import source.database as database
import importlib
import os
import glob
importlib.reload(parsers)
importlib.reload(database)
import pandas as pd

In [2]:
device = "cuda"
database_folder = "./database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

VD = database.VectorDatabase(device, database_folder)
VD.info()
VD.clear_collections()
VD.create_collection()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records
deleted data in Collection(name=documents)

`torch_dtype` is deprecated! Use `dtype` instead!

created collection: Collection(name=documents) with 0 documents

In [3]:
glob_pattern = os.path.join('.', 'data', '*')
files = glob.glob(glob_pattern)

for file in files:
   VD.add_documents(file)

.\data\demo_textfile.txt
- added 1 documents, 6 chunks
.\data\HW 1 - Cave Flyer.pdf
- added 1 documents, 3 chunks
.\data\HW 2 - Complex Numbers.pdf
- added 1 documents, 3 chunks
.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
- added 1 documents, 5 chunks
.\data\HW 4 - Linearization and Dynamic Response.pdf
- added 1 documents, 2 chunks
.\data\HW 5 - Exam 1 in Matlab.pdf
- added 1 documents, 3 chunks
.\data\HW 6 - Routh Array and Root Locus.pdf
- added 1 documents, 2 chunks
.\data\HW 7 - Design Challenges.pdf
- added 1 documents, 7 chunks
.\data\HW 8 - Nyquist Stability.pdf
- added 1 documents, 1 chunks
.\data\HW 9 - Stability Margins and Compensation.pdf
- added 1 documents, 1 chunks

In [4]:
VD.add_documents(files)

.\data\demo_textfile.txt
.\data\HW 1 - Cave Flyer.pdf
.\data\HW 2 - Complex Numbers.pdf
.\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
.\data\HW 4 - Linearization and Dynamic Response.pdf
.\data\HW 5 - Exam 1 in Matlab.pdf
.\data\HW 6 - Routh Array and Root Locus.pdf
.\data\HW 7 - Design Challenges.pdf
.\data\HW 8 - Nyquist Stability.pdf
.\data\HW 9 - Stability Margins and Compensation.pdf
- added 10 documents, 33 chunks

In [5]:
VD.info()

collections: [Collection(name=documents)]
Collection(name=documents) has 43 records

In [6]:
query ="how do I install matlab"
df_results = VD.search(query, k = 10)
df_results

found 10 similar documents

   distance                                           basename                                    id                                    id         author  chunk_idx                               page_lengths                                           fullpath tfidf               creation_date       source_type                                          file_hash                                    id                                    id                                              title                 upload_date           modification_date  N_chunks file_ext                             source_id pca                                           document
0  0.467617                              HW 1 - Cave Flyer.pdf  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  Sameer Shroff          0                           (974, 2735, 291)                       .\data\HW 1 - Cave Flyer.pdf    ()  2025-11-26 11:27:12.507327  chunked document  d235a1898843e3a439eabc58b387565f659900d5644604...  84d1843d-1bd1-53b8-ae55-2c2c939cdb37  84d1843d-1bd1-53b8-ae55-2c2c939cdb37                              HW 1 - Cave Flyer.pdf  2025-11-30 18:48:18.007915  2024-08-25 16:26:44.119668         3     .pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  ()  Carnegie Mellon University 24-451: Feedback Co...
1  0.477226                              HW 1 - Cave Flyer.pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  Sameer Shroff         -1                           (974, 2735, 291)                       .\data\HW 1 - Cave Flyer.pdf    ()  2025-11-26 11:27:12.507327     full document  d235a1898843e3a439eabc58b387565f659900d5644604...  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  18b8a5c1-0e02-5935-8acb-b6b32f32ae36                              HW 1 - Cave Flyer.pdf  2025-11-30 18:48:18.007915  2024-08-25 16:26:44.119668         0     .pdf  18b8a5c1-0e02-5935-8acb-b6b32f32ae36  ()  Carnegie Mellon University 24-451: Feedback Co...
2  0.712724                       HW 7 - Design Challenges.pdf  34d76a86-10c7-52c4-b9fa-a71985820b17  34d76a86-10c7-52c4-b9fa-a71985820b17  Sameer Shroff          3  (1352, 1462, 1842, 401, 1634, 1157, 1138)                .\data\HW 7 - Design Challenges.pdf    ()  2025-11-26 11:27:12.514347  chunked document  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  34d76a86-10c7-52c4-b9fa-a71985820b17  34d76a86-10c7-52c4-b9fa-a71985820b17                       HW 7 - Design Challenges.pdf  2025-11-30 18:48:19.969827  2022-10-23 12:31:27.302366         7     .pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  ()  Carnegie Mellon University 24-451: Feedback Co...
3  0.733412              HW 6 - Routh Array and Root Locus.pdf  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  Sameer Shroff          1                                (2191, 957)       .\data\HW 6 - Routh Array and Root Locus.pdf    ()  2025-11-26 11:27:12.513349  chunked document  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  c6aeca0f-6ea7-585e-b995-1cf9b71baef3  c6aeca0f-6ea7-585e-b995-1cf9b71baef3              HW 6 - Routh Array and Root Locus.pdf  2025-11-30 18:48:18.802212  2023-10-04 17:23:37.193000         2     .pdf  2c2a9853-3781-5770-8e9f-c5726b15291d  ()  • # 7c only.  Use Simulink.  Hint: 𝐾1 will be ...
4  0.748144                         HW 2 - Complex Numbers.pdf  31d1eafa-c729-54c6-ac3d-5255371c96e7  31d1eafa-c729-54c6-ac3d-5255371c96e7  Sameer Shroff          1                          (1937, 1550, 600)                  .\data\HW 2 - Complex Numbers.pdf    ()  2025-11-26 11:27:12.508334  chunked document  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  31d1eafa-c729-54c6-ac3d-5255371c96e7  31d1eafa-c729-54c6-ac3d-5255371c96e7                         HW 2 - Complex Numbers.pdf  2025-11-30 18:48:18.165540  2024-08-27 20:24:40.731488         3     .pdf  41fc35d3-e8dd-5ea0-9c4f-fea6a7d36787  ()  axis). \n7. Consider a set of points that form...
5  0.753956                       HW 7 - Design Challenges.pdf  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  Sameer Shroff          0  (1352, 1462, 1842, 401, 1634, 1157, 1138)                .\data\HW 7 - Design Challenges.pdf    ()  2025-11-26 11:27:12.514347  chunked document  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  a9b7e972-fbf0-5ff5-af3c-19fba77410f6  a9b7e972-fbf0-5ff5-af3c-19fba77410f6                       HW 7 - Design Challenges.pdf  2025-11-30 18:48:19.969827  2022-10-23 12:31:27.302366         7     .pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  ()  Carnegie Mellon University 24-451: Feedback Co...
6  0.753956                       HW 7 - Design Challenges.pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  Sameer Shroff         -1  (1352, 1462, 1842, 401, 1634, 1157, 1138)                .\data\HW 7 - Design Challenges.pdf    ()  2025-11-26 11:27:12.514347     full document  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  79afc125-4d4f-5e0b-9447-f0e0b3238bbd                       HW 7 - Design Challenges.pdf  2025-11-30 18:48:19.969827  2022-10-23 12:31:27.302366         0     .pdf  79afc125-4d4f-5e0b-9447-f0e0b3238bbd  ()  Carnegie Mellon University 24-451: Feedback Co...
7  0.755669  HW 3 - Laplace Transforms and Intro to Control...  2f69e529-3bc2-5a92-874b-b6721ac6adf4  2f69e529-3bc2-5a92-874b-b6721ac6adf4  Sameer Shroff          3                    (2363, 1621, 1323, 682)  .\data\HW 3 - Laplace Transforms and Intro to ...    ()  2025-11-26 11:27:12.509331  chunked document  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2f69e529-3bc2-5a92-874b-b6721ac6adf4  2f69e529-3bc2-5a92-874b-b6721ac6adf4  HW 3 - Laplace Transforms and Intro to Control...  2025-11-30 18:48:18.527408  2022-09-07 20:37:59.854000         5     .pdf  dc14db90-fbd5-55d7-bf3e-dbca0e531fe1  ()  Carnegie Mellon University 24-451: Feedback Co...
8  0.757500                        HW 5 - Exam 1 in Matlab.pdf  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  Sameer Shroff          0                         (1749, 2024, 1216)                 .\data\HW 5 - Exam 1 in Matlab.pdf    ()  2025-11-26 11:27:12.511332  chunked document  910573961d42ea022be07ca314325b4400a963f89e1795...  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce  66d92bf3-2b6b-5b92-b5a8-d52d9a70f6ce                        HW 5 - Exam 1 in Matlab.pdf  2025-11-30 18:48:18.731276  2024-09-25 17:53:25.497000         3     .pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334  ()  Carnegie Mellon University 24-451: Feedback Co...
9  0.757500                        HW 5 - Exam 1 in Matlab.pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334  8bf3b706-bed9-57bb-b088-6a6ca5278334  Sameer Shroff         -1                         (1749, 2024, 1216)                 .\data\HW 5 - Exam 1 in Matlab.pdf    ()  2025-11-26 11:27:12.511332     full document  910573961d42ea022be07ca314325b4400a963f89e1795...  8bf3b706-bed9-57bb-b088-6a6ca5278334  8bf3b706-bed9-57bb-b088-6a6ca5278334                        HW 5 - Exam 1 in Matlab.pdf  2025-11-30 18:48:18.731276  2024-09-25 17:53:25.497000         0     .pdf  8bf3b706-bed9-57bb-b088-6a6ca5278334  ()  Carnegie Mellon University 24-451: Feedback Co...

In [7]:
query ="what options do I have to install matlab in detail"
response = VD.query(query, k = 10)
print(response.content)

found 10 similar documents
You have the following options to install or run MATLAB:
1. Download and install MATLAB locally: You can download and install MATLAB by visiting the following link: https://www.cmu.edu/computing/software/all/matlab/.
2. Run MATLAB online through a browser: You can access MATLAB online through a browser at https://www.mathworks.com/products/matlab-online.html.
3. Run MATLAB through a Virtual Andrew session: You can run MATLAB through a Virtual Andrew session by following the instructions at https://www.cmu.edu/computing/services/endpoint/software/managed-desktops/how-to/virtual-andrew.html.

(source: HW 1 - Cave Flyer.pdf)

In [21]:
import pandas as pd
import ast




def results_to_df(results, document_length_limit = None):

    d = {}
    if 'distances' in results.keys():
        d['distance'] = results['distances']
    if 'ids' in results.keys():
        d['id'] = results['ids']
    if 'documents' in results.keys():  
        d['document'] = results['documents']
    if 'embeddings' in results.keys():
        d['embedding'] = [row for row in results['embeddings']]
    df = pd.DataFrame.from_dict(d)

    if 'metadatas' in results.keys():
        df_metadata = pd.DataFrame(results['metadatas'], index = range(len(df))).drop(columns = 'id')
        df = pd.concat([df, df_metadata], axis = 1).reset_index(drop = True)

    datetime_format =  r"%Y-%m-%d %H:%M:%S.%f"
    type_converter = {}
    type_converter['creation_date'] = lambda x:  pd.to_datetime(x, format = datetime_format)
    type_converter['upload_date'] = lambda x:  pd.to_datetime(x, format = datetime_format)
    type_converter['modification_date'] = lambda x:  pd.to_datetime(x, format = datetime_format)
    type_converter['page_lengths'] = lambda x:  x.apply(ast.literal_eval)
    type_converter['document'] = lambda x:  x.str[:document_length_limit]

    for col in df.columns:
        if col in type_converter.keys():
            df[col] = type_converter[col](df[col])

    return df


results = VD.collection.get(
        limit=10,
        offset=0,
        include=['documents', 'metadatas', 'embeddings'] # Specify what to include
    )


df = results_to_df(results, document_length_limit= 6)

df

                                     id document                                          embedding      page_lengths       source_type                      fullpath                  title tfidf  N_chunks  chunk_idx          modification_date         author              creation_date                                          file_hash                             source_id file_ext pca               basename                upload_date
0  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a   In Con  [-0.07415771484375, 0.048370361328125, -0.0075...           (8149,)     full document      .\data\demo_textfile.txt      demo_textfile.txt    ()         0         -1 2025-11-29 23:40:34.881779                2025-11-29 23:39:54.799670  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt  ()      demo_textfile.txt 2025-11-30 18:48:17.902228
1  d00a351a-96b3-560b-8b31-f7dab9abc247   In Con  [-0.023284912109375, 0.0200347900390625, 0.014...           (8149,)  chunked document      .\data\demo_textfile.txt      demo_textfile.txt    ()         6          0 2025-11-29 23:40:34.881779                2025-11-29 23:39:54.799670  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt  ()      demo_textfile.txt 2025-11-30 18:48:17.902228
2  ac16fb33-1007-5f21-badf-51326739eae1   We hol  [-0.08221435546875, 0.09283447265625, -0.04080...           (8149,)  chunked document      .\data\demo_textfile.txt      demo_textfile.txt    ()         6          1 2025-11-29 23:40:34.881779                2025-11-29 23:39:54.799670  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt  ()      demo_textfile.txt 2025-11-30 18:48:17.902228
3  6e75dfa6-61ce-5d73-9f0b-97e593b36e70   He has  [0.005073546897619963, 0.01837158203125, 0.054...           (8149,)  chunked document      .\data\demo_textfile.txt      demo_textfile.txt    ()         6          2 2025-11-29 23:40:34.881779                2025-11-29 23:39:54.799670  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt  ()      demo_textfile.txt 2025-11-30 18:48:17.902228
4  7f7ee21b-13c6-5bd6-927b-45ae4a2d217a   He has  [-0.02313232421875, 0.050994873046875, 0.01861...           (8149,)  chunked document      .\data\demo_textfile.txt      demo_textfile.txt    ()         6          3 2025-11-29 23:40:34.881779                2025-11-29 23:39:54.799670  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt  ()      demo_textfile.txt 2025-11-30 18:48:17.902228
5  2443d291-d7bc-5b92-a554-04af388319a1   He has  [-0.02511596865952015, 0.079833984375, 0.00570...           (8149,)  chunked document      .\data\demo_textfile.txt      demo_textfile.txt    ()         6          4 2025-11-29 23:40:34.881779                2025-11-29 23:39:54.799670  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt  ()      demo_textfile.txt 2025-11-30 18:48:17.902228
6  6387ac27-fb24-5a6b-9830-4c22a1923477   We, th  [-0.0576477088034153, -0.0270538330078125, 0.0...           (8149,)  chunked document      .\data\demo_textfile.txt      demo_textfile.txt    ()         6          5 2025-11-29 23:40:34.881779                2025-11-29 23:39:54.799670  85ed45c9a6c1555ac04855ce9f4aad1432f0f6888b3721...  c480bfc2-e3ea-5aa5-bbf5-7ce14b5c173a     .txt  ()      demo_textfile.txt 2025-11-30 18:48:17.902228
7  18b8a5c1-0e02-5935-8acb-b6b32f32ae36   Carneg  [-0.021697998046875, -0.01471710205078125, -0....  (974, 2735, 291)     full document  .\data\HW 1 - Cave Flyer.pdf  HW 1 - Cave Flyer.pdf    ()         0         -1 2024-08-25 16:26:44.119668  Sameer Shroff 2025-11-26 11:27:12.507327  d235a1898843e3a439eabc58b387565f659900d5644604...  18b8a5c1-0e02-5935-8acb-b6b32f32ae36     .pdf  ()  HW 1 - Cave Flyer.pdf 2025-11-30 18:48:18.007915
8  84d1843d-1bd1-53b8-ae55-2c2c939cdb37   Carneg  [-0.020050048828125, -0.002834320068359375, -0...  (974, 2735, 291)  chunked document  .\data\HW 1 - Cave Flyer.pdf  HW 1 - Cave Flyer.pdf    ()         3          0 2024-08-25 16:26:44.119668  Sameer Shroff 2025-11-26 11:27:12.507327  d235a1898843e3a439eabc58b387565f659900d5644604...  18b8a5c1-0e02-5935-8acb-b6b32f32ae36     .pdf  ()  HW 1 - Cave Flyer.pdf 2025-11-30 18:48:18.007915
9  a6a533b9-7542-5de9-997e-a8bf62a2567d   Carneg  [0.0684204176068306, 0.0518188513815403, -0.07...  (974, 2735, 291)  chunked document  .\data\HW 1 - Cave Flyer.pdf  HW 1 - Cave Flyer.pdf    ()         3          1 2024-08-25 16:26:44.119668  Sameer Shroff 2025-11-26 11:27:12.507327  d235a1898843e3a439eabc58b387565f659900d5644604...  18b8a5c1-0e02-5935-8acb-b6b32f32ae36     .pdf  ()  HW 1 - Cave Flyer.pdf 2025-11-30 18:48:18.007915

In [10]:
labels, inertia, df_pca = DS.run_kmeans(n_clusters = 3)
df_pca

NameError: name 'DS' is not defined

In [ ]:
id = DS.collection.get(limit = 1)['ids'][0]
df = DS.search_by_id(id, k =10, where = {'source_type':'full document'})
print(df)

       distance                                           basename                                    id  N_chunks                             source_id               creation_date    source_type                               page_lengths file_ext  chunk_idx                 upload_date                                                pca         author                                           fullpath           modification_date                                               hash                                           document
0  3.576279e-07                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc         0  7353459a-33c2-544c-81f2-4e8877cddfcc  2025-11-26 11:27:12.507327  full document                           [974, 2735, 291]     .pdf         -1  2025-11-28 23:46:52.237318  [-0.09745040145997666, 0.0239056972048863, 0.4...  Sameer Shroff                       .\data\HW 1 - Cave Flyer.pdf  2024-08-25 16:26:44.119668  d235a1898843e3a439eabc58b387565f659900d5644604...  Carnegie Mellon University 24-451: Feedback Co...
1  4.009807e-01                       HW 7 - Design Challenges.pdf  8a5a4e88-6b39-5898-8682-6953f1a90da7         0  8a5a4e88-6b39-5898-8682-6953f1a90da7  2025-11-26 11:27:12.514347  full document  [1352, 1462, 1842, 401, 1634, 1157, 1138]     .pdf         -1  2025-11-28 23:46:53.688009  [-0.033397547548804814, -0.2070083680654652, -...  Sameer Shroff                .\data\HW 7 - Design Challenges.pdf  2022-10-23 12:31:27.302366  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  Carnegie Mellon University 24-451: Feedback Co...
2  4.437943e-01                        HW 5 - Exam 1 in Matlab.pdf  aca9ef5a-8288-54e0-8231-4268d682efd2         0  aca9ef5a-8288-54e0-8231-4268d682efd2  2025-11-26 11:27:12.511332  full document                         [1749, 2024, 1216]     .pdf         -1  2025-11-28 23:46:53.285213  [-0.1904676541166523, -0.13307204027003494, -0...  Sameer Shroff                 .\data\HW 5 - Exam 1 in Matlab.pdf  2024-09-25 17:53:25.497000  910573961d42ea022be07ca314325b4400a963f89e1795...  Carnegie Mellon University 24-451: Feedback Co...
3  4.689484e-01      HW 9 - Stability Margins and Compensation.pdf  0eacdba8-9efd-59ce-816a-366d8cf519a9         0  0eacdba8-9efd-59ce-816a-366d8cf519a9  2025-11-26 11:27:12.516346  full document                                     [1682]     .pdf         -1  2025-11-28 23:46:55.123613  [-0.1715749821662112, -0.300254976348345, -0.0...  Sameer Shroff  .\data\HW 9 - Stability Margins and Compensati...  2024-10-23 09:08:41.972093  9a6a2b527b59828fc47564fb9c95b4c5a24597e9d328fb...  Carnegie Mellon University 24-451: Feedback Co...
4  4.818359e-01                       HW 8 - Nyquist Stability.pdf  b58c24f9-36c9-5332-8d5c-c363e1ab26be         0  b58c24f9-36c9-5332-8d5c-c363e1ab26be  2025-11-26 11:27:12.515346  full document                                     [1230]     .pdf         -1  2025-11-28 23:46:54.962095  [-0.012212717280018255, -0.3432190166218551, -...  Sameer Shroff                .\data\HW 8 - Nyquist Stability.pdf  2022-10-23 12:32:44.015152  4623910fab2a942e48d87d03a7a14a78f2a37819210fa8...  Carnegie Mellon University 24-451: Feedback Co...
5  4.869819e-01      HW 4 - Linearization and Dynamic Response.pdf  eb7dbac7-1c3e-59c6-ba88-06afd7217d81         0  eb7dbac7-1c3e-59c6-ba88-06afd7217d81  2025-11-26 11:27:12.510332  full document                                [1457, 659]     .pdf         -1  2025-11-28 23:46:53.097486  [-0.14765964738550874, -0.039737873715005353, ...  Sameer Shroff  .\data\HW 4 - Linearization and Dynamic Respon...         2020-09-23 07:28:23  c1f105d224226dbd40b5158fd249c8a06f7711bbd80f9b...  Carnegie Mellon University 24-451: Feedback Co...
6  4.988220e-01  HW 3 - Laplace Transforms and Intro to Control...  92843a15-ddf5-51b5-b851-ed3b159a4e25         0  92843a15-ddf5-51b5-b851-ed3b159a4e25  2025-11-26 11:27:12.509331  full document                    [2363, 1621, 1323, 682]     .pdf         -1  2025-11-28 23:46:52.818393  [-0.20201848082993792, -0.3458179490897861, 0....  Sameer Shroff  .\data\HW 3 - Laplace Transforms and Intro to ...  2022-09-07 20:37:59.854000  b907d592332785225f53963d7e64d3379ba273adfb78ba...  Carnegie Mellon University 24-451: Feedback Co...
7  5.028403e-01              HW 6 - Routh Array and Root Locus.pdf  7f0fa013-0289-5477-987f-29511a387622         0  7f0fa013-0289-5477-987f-29511a387622  2025-11-26 11:27:12.513349  full document                                [2191, 957]     .pdf         -1  2025-11-28 23:46:53.506439  [-0.12312544081913634, -0.272924053555092, -0....  Sameer Shroff       .\data\HW 6 - Routh Array and Root Locus.pdf  2023-10-04 17:23:37.193000  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  Carnegie Mellon University 24-451: Feedback Co...
8  5.448520e-01                         HW 2 - Complex Numbers.pdf  3dc8bb69-454a-535c-9815-02ae4e274a4f         0  3dc8bb69-454a-535c-9815-02ae4e274a4f  2025-11-26 11:27:12.508334  full document                          [1937, 1550, 600]     .pdf         -1  2025-11-28 23:46:52.594257  [0.37945585105624025, -0.23634997581372721, 0....  Sameer Shroff                  .\data\HW 2 - Complex Numbers.pdf  2024-08-27 20:24:40.731488  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  Carnegie Mellon University 24-451: Feedback Co...

In [ ]:
import pandas as pd

id = DS.collection.get(limit = 1)['ids'][0]
r = DS.collection.get(id, include = ['embeddings'])
embedding = r['embeddings']
results = DS.collection.query(query_embeddings=embedding, include=['distances', 'metadatas', 'documents'])
df_results= shroff_rag._results_to_df(results)[0]
df_results = df_results.sort_values('distance')
df_results

       distance                                           basename                                    id               creation_date  chunk_idx file_ext                                                pca       source_type                             source_id  N_chunks                 upload_date                                           fullpath                               page_lengths         author                                               hash           modification_date                                           document
0  3.576279e-07                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc  2025-11-26 11:27:12.507327         -1     .pdf  [-0.09745040145997666, 0.0239056972048863, 0.4...     full document  7353459a-33c2-544c-81f2-4e8877cddfcc         0  2025-11-28 23:46:52.237318                       .\data\HW 1 - Cave Flyer.pdf                           [974, 2735, 291]  Sameer Shroff  d235a1898843e3a439eabc58b387565f659900d5644604...  2024-08-25 16:26:44.119668  Carnegie Mellon University 24-451: Feedback Co...
1  6.156325e-03                              HW 1 - Cave Flyer.pdf  286dd1fb-d5c2-5c3c-9e1f-65edc0aeb8df  2025-11-26 11:27:12.507327          0     .pdf  [-0.09567961068889143, 0.029872929615534234, 0...  chunked document  7353459a-33c2-544c-81f2-4e8877cddfcc         5  2025-11-28 23:46:52.237318                       .\data\HW 1 - Cave Flyer.pdf                           [974, 2735, 291]  Sameer Shroff  d235a1898843e3a439eabc58b387565f659900d5644604...  2024-08-25 16:26:44.119668  Carnegie Mellon University 24-451: Feedback Co...
2  3.589152e-01  HW 3 - Laplace Transforms and Intro to Control...  199f260c-8442-5ee7-922c-c5dcdee6441e  2025-11-26 11:27:12.509331          1     .pdf  [-0.14951696490511152, 0.02112588252143664, 0....  chunked document  92843a15-ddf5-51b5-b851-ed3b159a4e25         8  2025-11-28 23:46:52.818393  .\data\HW 3 - Laplace Transforms and Intro to ...                    [2363, 1621, 1323, 682]  Sameer Shroff  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2022-09-07 20:37:59.854000  not discussed in class).   \n4. Typical contro...
3  3.937255e-01                       HW 7 - Design Challenges.pdf  1655f1d1-9623-577e-8de7-e4a6cb26cf74  2025-11-26 11:27:12.514347          0     .pdf  [-0.02772100684287592, -0.20169627866021034, -...  chunked document  8a5a4e88-6b39-5898-8682-6953f1a90da7        13  2025-11-28 23:46:53.688009                .\data\HW 7 - Design Challenges.pdf  [1352, 1462, 1842, 401, 1634, 1157, 1138]  Sameer Shroff  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  Carnegie Mellon University 24-451: Feedback Co...
4  4.009807e-01                       HW 7 - Design Challenges.pdf  8a5a4e88-6b39-5898-8682-6953f1a90da7  2025-11-26 11:27:12.514347         -1     .pdf  [-0.033397547548804814, -0.2070083680654652, -...     full document  8a5a4e88-6b39-5898-8682-6953f1a90da7         0  2025-11-28 23:46:53.688009                .\data\HW 7 - Design Challenges.pdf  [1352, 1462, 1842, 401, 1634, 1157, 1138]  Sameer Shroff  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  Carnegie Mellon University 24-451: Feedback Co...
5  4.276317e-01              HW 6 - Routh Array and Root Locus.pdf  6d68a7b5-9426-57b7-8336-d3682cf2bd87  2025-11-26 11:27:12.513349          2     .pdf  [-0.031672400647115385, -0.12534593047786177, ...  chunked document  7f0fa013-0289-5477-987f-29511a387622         4  2025-11-28 23:46:53.506439       .\data\HW 6 - Routh Array and Root Locus.pdf                                [2191, 957]  Sameer Shroff  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  2023-10-04 17:23:37.193000  Do problems:  \n• # 4.  Hint: for the closed l...
6  4.437943e-01                        HW 5 - Exam 1 in Matlab.pdf  aca9ef5a-8288-54e0-8231-4268d682efd2  2025-11-26 11:27:12.511332         -1     .pdf  [-0.1904676541166523, -0.13307204027003494, -0...     full document  aca9ef5a-8288-54e0-8231-4268d682efd2         0  2025-11-28 23:46:53.285213                 .\data\HW 5 - Exam 1 in Matlab.pdf                         [1749, 2024, 1216]  Sameer Shroff  910573961d42ea022be07ca314325b4400a963f89e1795...  2024-09-25 17:53:25.497000  Carnegie Mellon University 24-451: Feedback Co...
7  4.439000e-01                       HW 7 - Design Challenges.pdf  6eadf3ed-8569-5c4f-b491-ddc82800b339  2025-11-26 11:27:12.514347          4     .pdf  [-0.14179743010144524, -0.10353334333602214, -...  chunked document  8a5a4e88-6b39-5898-8682-6953f1a90da7        13  2025-11-28 23:46:53.688009                .\data\HW 7 - Design Challenges.pdf  [1352, 1462, 1842, 401, 1634, 1157, 1138]  Sameer Shroff  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  Carnegie Mellon University 24-451: Feedback Co...
8  4.447445e-01                        HW 5 - Exam 1 in Matlab.pdf  eeb26b35-3cab-51fa-a773-66e4a9e2eceb  2025-11-26 11:27:12.511332          0     .pdf  [-0.17971123092363642, -0.13044921506346033, -...  chunked document  aca9ef5a-8288-54e0-8231-4268d682efd2         7  2025-11-28 23:46:53.285213                 .\data\HW 5 - Exam 1 in Matlab.pdf                         [1749, 2024, 1216]  Sameer Shroff  910573961d42ea022be07ca314325b4400a963f89e1795...  2024-09-25 17:53:25.497000  Carnegie Mellon University 24-451: Feedback Co...
9  4.689484e-01      HW 9 - Stability Margins and Compensation.pdf  0eacdba8-9efd-59ce-816a-366d8cf519a9  2025-11-26 11:27:12.516346         -1     .pdf  [-0.1715749821662112, -0.300254976348345, -0.0...     full document  0eacdba8-9efd-59ce-816a-366d8cf519a9         0  2025-11-28 23:46:55.123613  .\data\HW 9 - Stability Margins and Compensati...                                     [1682]  Sameer Shroff  9a6a2b527b59828fc47564fb9c95b4c5a24597e9d328fb...  2024-10-23 09:08:41.972093  Carnegie Mellon University 24-451: Feedback Co...