In [58]:
import os
os.environ["OMP_NUM_THREADS"] = "1"  # avoid windows memory leak in sklearn kmeans, set before Kmeans importimport parsers
import shroff_rag
import importlib
import os
import glob
import parsers

importlib.reload(shroff_rag)
importlib.reload(parsers)

In [59]:
device = "cuda"
database_folder = "./database_data"
os.environ["GOOGLE_API_KEY"] = "AIzaSyCp2r7wKvf_aNLc1gxzJTdhLrVAwaS-0WM"

DS = shroff_rag.DataStore(device, database_folder)
DS.info()
DS.clear_collections()
DS.create_collection()

collections: [Collection(name=documents)]
deleted data in Collection(name=documents)
created collection: Collection(name=documents) with 0 documents

In [60]:
glob_pattern = os.path.join('.', 'data', '*.pdf')
files = glob.glob(glob_pattern)

for file in files:
   DS.add_document(file)

- added .\data\HW 1 - Cave Flyer.pdf
   - added 5 chunks from .\data\HW 1 - Cave Flyer.pdf
- added .\data\HW 2 - Complex Numbers.pdf
   - added 6 chunks from .\data\HW 2 - Complex Numbers.pdf
- added .\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
   - added 8 chunks from .\data\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf
- added .\data\HW 4 - Linearization and Dynamic Response.pdf
   - added 3 chunks from .\data\HW 4 - Linearization and Dynamic Response.pdf
- added .\data\HW 5 - Exam 1 in Matlab.pdf
   - added 7 chunks from .\data\HW 5 - Exam 1 in Matlab.pdf
- added .\data\HW 6 - Routh Array and Root Locus.pdf
   - added 4 chunks from .\data\HW 6 - Routh Array and Root Locus.pdf
- added .\data\HW 7 - Design Challenges.pdf
   - added 13 chunks from .\data\HW 7 - Design Challenges.pdf
- added .\data\HW 8 - Nyquist Stability.pdf
   - added 2 chunks from .\data\HW 8 - Nyquist Stability.pdf
- added .\data\HW 9 - Stability Margins and Compensation.pdf
   - added 2 chunks from .\data\HW 9 - Stability Margins and Compensation.pdf

In [61]:
DS.info()

collections: [Collection(name=documents)]

In [62]:
query ="how do I install matlab"
df_results = DS.search(query, k = 10)
df_results

{'ids': [['2df0e1d4-62c2-4ba8-9dac-072608061909', '7353459a-33c2-544c-81f2-4e8877cddfcc', '243c67fe-7154-4674-a8fd-8223d484fe33', 'cb74c11c-d4d2-4cc3-ac55-f73a76ef73a6', 'd3773e72-d96d-4905-930d-0d24df8241e1', '2e666691-292c-4b9b-b874-21f3d714abc6', '4e110d05-611f-4f6b-bc2e-491ff0897201', '2ed64a78-4324-428b-8c4e-405716135045', '06122fd8-cffe-4a86-9349-a3d8d59dc75f', 'd22c6a9a-689c-447a-a62b-58d5a9db779d']], 'embeddings': None, 'documents': [['Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters \n \n \n \n \n \n \n \n\nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nQuestions: \n1) Your task is to design a controller for the system.  Find the controller file with function  \nfunction F = shroff_controller(y, vy, ytop, ybot) \n \n% Goal - use the input variables to calculate a desired output force F. \n  \n% ytop:  a 1 x 21 vector with positions of the top wall.  ytop(21) is the \nfurthest from the ship. \n% ybot:  a 1 x 21 vector with positions of the bottom wall.  ybot(21) is the \nfurthest from the ship. \n% y: Current position of the ship \n% vy: Current velocity of the ship \n% F: Output force to apply in the vertical direction (can be -1 <= F <= 1, \ncode will enforce this) \n \nRead and understand all of the inputs and output of the function.   \n \n2) In words, describe how you would avoid hitting walls of the cave.  Hint:  You could say \nsomething like if you get within x units of either wall, set F to push the ship the other way.  \nAn alternative scheme would be to try to stay in the middle of the path.   \n3) Convert your scheme to mathematical equations.  Remember, you can only work with the \ninput values in the function F = yourname_controller(ytop, ybot, y, vy).  Add \ncode to the function representing these equations.  Make sure to rename the .m file with \nyour new function name yourname_controller. \n4) Run the code with your controller.  How well did you do?  Describe your process for \nsystematically tuning the controller (for example, how did you use educated guesses to \ntune the strength of forces?).  Try a different control scheme if needed. \n5) Run levels [1, 2, 4, 8, 16, …., 2048] by changing M.levels.  Record the impact time t \nfor each level and take the average.  Report the individual times on the class spreadsheet \n(https://docs.google.com/spreadsheets/d/185q_onHT4oSUj3FxN-12PGQVs_D_wGWYxbHLlN0gWTM/edit?usp=sharing). \n6) In a few sentences describe important factors that were not taken into account in this \nsimulation.  Hint: think about sensor noise, delay in changing the thrust, etc.  Could your \ncontroller be used on different ships?  If the mass of a ship was twice as much, or the cave \nwall shapes were very different (more jagged for example), do you think your controller \nwould have to be adjusted? \n7) Submit answers to these questions as well as controller code on Canvas. \nOptional Upload: \nUpload your controller file here.  We will demo and discuss some of these after the assignment \nis due. \nhttps://forms.gle/pNfxWdQJNpRe6MuE6 \n \n \nOptional Bonus: \nAdd a loop in the code to quickly test your controller on levels [1, 2, 4, 8, …, 2048].  Save the \ntimes in a vector, and take the average.  Try to optimize the average time until collision by \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 3 \nchanging parameter values in your code.  Show that you have found a local minima by \ndemonstrating that by either increasing or decreasing one of the parameters, the average time \ndecreases. \n \n', 'j. What happens as K increases?  Show and example output and qualitatively explain the \nchanges (explain changes in rise time and overshoot). \nk. For part (b), there were several ways to estimate the value of K that results in the plot \ndisplayed.  Using the value of K you calculated on your exam, show the scope output.  \nHow close were you? \nQuestion 7 \nl. Using Matlab (not Simulink), define 𝐺1 and 𝐺2.  Use the commands impulse(), step(), \nand lsim() to recreate the 6 plots.  Review our code examples if you forget how to apply \nan arbitrary input using lsim(). \nQuestion 8 \nm. Use the functions pzmap() and pzplot() to calculate the poles and zeros of G and plot \nthem in the complex plane. \nn. Vary K from 0 to 10 (in increments of .2 or smaller).  Calculate the 2 poles of 𝐺2 for each \nvalue of K (Use a loop to make this easy). \no. Plot the poles as a function of K on the complex plane.  Label 3 regions – (1) when the', 'not discussed in class).   \n4. Typical control systems have requirements on stability, tracking, disturbance rejection, \nand robustness.  Briefly explain each one (hint: Chapter 1 discusses these). \nLaplace Transforms (Section 3.1) \n5. Book problem 3.3 (use a Laplace table) \n6. Book problem 3.7(a) by hand (can use a Laplace table) \n7. Book problem 3.7(d) using Matlab.  Hint: use ilaplace() \n8. Book problem 3.9(a) \n \nSystem Identification \nIdentifying and modeling dynamic systems is often a prerequisite to being able to apply control.  \nIn this case study, you will create models for 10 dynamic systems.  Download file \n“RunExperiment.p” from Canvas, and make sure it is in your working directory.  Understand the \ninputs and outputs of the function, listed below: \n \n>> help RunExperiment \n RunExperiment(id, U, make_plot):  Runs a system simulation for input matrix U \n    inputs:  id: integer from 1 to 10 that sets what system to simulate', 'Do problems:  \n• # 4.  Hint: for the closed loop transfer function T, sensitivity is defined as \n𝐴\n𝑇 (\n𝑑𝑇\n𝑑𝐴), \n𝑎\n𝑇 (\n𝑑𝑇\n𝑑𝑎), \nor \n𝛽\n𝑇 (\n𝑑𝑇\n𝑑𝛽) for each part, respectively.  Read section 4.1.4 of the textbook for more \ndetails.  You can use the Matlab symbolic toolbox to help with the algebra if necessary.  \n• # 7c only.  Use Simulink.  Hint: 𝐾1 will be in the 1000-1500 range to obtain the desired \nstep overshoot, and the steady state error to 𝑟 = 5𝑡 should be around 0.3.    \n• # 10.  For part (b), you can use Matlab function routh.m found at: \nhttps://www.mathworks.com/matlabcentral/fileexchange/58-routh-m \n• # 29.  Hint: use the Matlab symbolic toolbox to make the algebra trivial. \n \nRoot-Locus Design Method (Chapter 5) \n \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nDo the following book problems .  Note that you can use the Matlab function rlocus( ) for any of', 'complex number should you multiply by?  Show this works using Matlab. \n \nNewton’s Method \nNewton’s method can be used to find the roots of a function.  One starts with an initial guess \n𝑥0.  The guess is updated as  \n𝑥𝑛+1 = 𝑥𝑛 − 𝑓(𝑥𝑛)\n𝑓′(𝑥𝑛) \n \n8. Consider the polynomial  \n𝑓(𝑥) = 𝑥3 + 1 \na. Use the Matlab command roots() to find the roots of the polynomial (𝑝1, 𝑝2, 𝑝3). \nb. Analytically compute 𝑓′(𝑥). \nc. Pick a starting value 𝑥0,1 from the complex plane and show it converges to root  \n𝑝1 using Newton’s method.  Similarly show different starting values 𝑥0,2 and 𝑥0,3 \nconverge to 𝑝2 and 𝑝3, respectively.  Plot each sequence of values 𝑥𝑛,𝑖 in the \ncomplex plane and show they terminate at 𝑝𝑖. \nOptional Bonus Problems:  \n9. You wish to first scale the shape by factor 𝛼 and then rotate it about an arbitrary point \n𝑐1 + 𝑐2𝑗 by 𝜃 degrees.  Describe your methodology (equations) for doing this using \ncomplex algebra, and show it works in Matlab for 𝛼 = 2, 𝑐1 = 3, 𝑐2 = 1, 𝜃 = 30°.', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 4 \n \nIf optimizing programmatically, it is much easier using Matlab transfer functions with \nstepinfo() rather than using Simulink.   \n \nMy optimal solution has a rise time of 0.1399 seconds.  Can you beat it? \n \n \n  \n0 0.2 0.4 0.6 0.8 1 1.2 1.4 1.6 1.8 2\n0\n5\n10\n15\n20\n25\n30\n35 Current due to 6*u(t) input', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 7 \nDesign Challenges \n \nThe following homework consists of 4 design challenges of varying levels of difficulty.  I suggest \ncompleting all required steps before attempting any optional bonus problems. \n \n \nProblem 1 \nConsider the following block diagram: \n \n \na) Determine the loop gain of the system. \nb) Determine the system type. \nc) Determine the steady state error due to step, ramp, and parabolic inputs as functions of \n𝐴. \nd) Consider a unit step input.  How does the % overshoot vary as a function of 𝐴?  Use a \nroot locus plot to aid your explanation (you can use rlocus in Matlab – remember the \nequation for the poles must be in root locus form).  Also show the simulation output at \n2 values of 𝐴.   \ne) For what values of 𝐴 is the system stable?  Use a root locus plot or Routh array to aid \nyour explanation (you can use rlocus() or routh() in Matlab).   \n \nProblem 2', "inputs and outputs of the function, listed below: \n \n>> help RunExperiment \n RunExperiment(id, U, make_plot):  Runs a system simulation for input matrix U \n    inputs:  id: integer from 1 to 10 that sets what system to simulate \n             U:  [Nt x Nu] input matrix, where Nt is the number of \n             timepoints and Nu is the number of inputs for the system. \n             Each column is a input signal. \n             make_plot: Boolean for if a plot should be generated \n    outputs: X:  [Nt x Nx] output matrix, where Nt is the number of \n             timepoints and Nx is the number of states.  Each column is how that \n             state evolves with time. \n \n  For example, to run system 5 with a step input, we could write something like \n \nt = (0:.1:10)'; \nU = ones(length(t), 1).*heaviside(t-5); \nX = RunExperiment(5, U, true); \n \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2", '𝑐1 + 𝑐2𝑗 by 𝜃 degrees.  Describe your methodology (equations) for doing this using \ncomplex algebra, and show it works in Matlab for 𝛼 = 2, 𝑐1 = 3, 𝑐2 = 1, 𝜃 = 30°. \n \nExample output: \n \n \n10. Consider the polynomial  \n𝑓(𝑥) = 𝑥3 + 1 \nAnd a square in the complex plane 𝑆 = 𝑎 + 𝑏𝑗, where −1 ≤ 𝑎 ≤ 1 and −1 ≤ 𝑏 ≤ 1 \na. Using Netwon’s method, map regions of 𝑆 to the root they terminate at.  Hint: \ncreate a mesh of points in 𝑆 that represent starting points, and run Newton’s \n1 1.5 2 2.5 3 3.5 4\n0\n0.5\n1\n1.5\n2\nCarnegie Mellon University 24-451: Feedback Control Systems\n Instructor: Dr. Sameer Shroff \n 3 \nmethod on each of these points.  You may want to vectorize the calculations.  \nThere may be some points that never converge, which is a known limitation to \nNewton’s method.  For these points, you can ignore them or return the pole as \nNaN.   \nb. Make a plot in the complex plane showing these regions.  For example, you']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'upload_date': '2025-11-28 19:24:50.627433', 'pca': '', 'source_id': '7353459a-33c2-544c-81f2-4e8877cddfcc', 'basename': 'HW 1 - Cave Flyer.pdf', 'author': 'Sameer Shroff', 'chunk_idx': 0, 'hash': 'd235a1898843e3a439eabc58b387565f659900d564460438304b195186542fe6', 'modification_date': '2024-08-25 16:26:44.119668', 'page_lengths': '[974, 2735, 291]', 'source_type': 'chunked document', 'fullpath': '.\\data\\HW 1 - Cave Flyer.pdf', 'N_chunks': 5, 'creation_date': '2025-11-26 11:27:12.507327', 'file_ext': '.pdf'}, {'upload_date': '2025-11-28 19:24:50.627433', 'pca': '', 'fullpath': '.\\data\\HW 1 - Cave Flyer.pdf', 'modification_date': '2024-08-25 16:26:44.119668', 'source_id': '7353459a-33c2-544c-81f2-4e8877cddfcc', 'creation_date': '2025-11-26 11:27:12.507327', 'file_ext': '.pdf', 'N_chunks': 0, 'source_type': 'full document', 'hash': 'd235a1898843e3a439eabc58b387565f659900d564460438304b195186542fe6', 'chunk_idx': -1, 'basename': 'HW 1 - Cave Flyer.pdf', 'page_lengths': '[974, 2735, 291]', 'author': 'Sameer Shroff'}, {'source_type': 'chunked document', 'fullpath': '.\\data\\HW 5 - Exam 1 in Matlab.pdf', 'basename': 'HW 5 - Exam 1 in Matlab.pdf', 'hash': '910573961d42ea022be07ca314325b4400a963f89e1795c1b5ed92d7968b9d54', 'upload_date': '2025-11-28 19:24:51.669425', 'N_chunks': 7, 'modification_date': '2024-09-25 17:53:25.497000', 'creation_date': '2025-11-26 11:27:12.511332', 'source_id': 'aca9ef5a-8288-54e0-8231-4268d682efd2', 'chunk_idx': 3, 'author': 'Sameer Shroff', 'pca': '', 'page_lengths': '[1749, 2024, 1216]', 'file_ext': '.pdf'}, {'chunk_idx': 1, 'source_type': 'chunked document', 'file_ext': '.pdf', 'creation_date': '2025-11-26 11:27:12.509331', 'source_id': '92843a15-ddf5-51b5-b851-ed3b159a4e25', 'basename': 'HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf', 'N_chunks': 8, 'hash': 'b907d592332785225f53963d7e64d3379ba273adfb78baed001d72a0dc604c73', 'page_lengths': '[2363, 1621, 1323, 682]', 'author': 'Sameer Shroff', 'pca': '', 'upload_date': '2025-11-28 19:24:51.228459', 'modification_date': '2022-09-07 20:37:59.854000', 'fullpath': '.\\data\\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf'}, {'author': 'Sameer Shroff', 'source_id': '7f0fa013-0289-5477-987f-29511a387622', 'pca': '', 'modification_date': '2023-10-04 17:23:37.193000', 'chunk_idx': 2, 'fullpath': '.\\data\\HW 6 - Routh Array and Root Locus.pdf', 'page_lengths': '[2191, 957]', 'N_chunks': 4, 'upload_date': '2025-11-28 19:24:51.892720', 'source_type': 'chunked document', 'file_ext': '.pdf', 'hash': 'f1e82092a15f30fd7579130c8628ec70ff6926c6171f43166a0f01edbb9cf0f1', 'basename': 'HW 6 - Routh Array and Root Locus.pdf', 'creation_date': '2025-11-26 11:27:12.513349'}, {'hash': '2c913fd6cc22e915214e21fca277d2db112d01b118af2be89f67edfeafdaf39e', 'modification_date': '2024-08-27 20:24:40.731488', 'pca': '', 'file_ext': '.pdf', 'author': 'Sameer Shroff', 'basename': 'HW 2 - Complex Numbers.pdf', 'fullpath': '.\\data\\HW 2 - Complex Numbers.pdf', 'creation_date': '2025-11-26 11:27:12.508334', 'upload_date': '2025-11-28 19:24:50.814526', 'source_type': 'chunked document', 'chunk_idx': 3, 'source_id': '3dc8bb69-454a-535c-9815-02ae4e274a4f', 'page_lengths': '[1937, 1550, 600]', 'N_chunks': 6}, {'hash': 'abec6a608c256b197114106e8843696d0ea0cf2fff87109f59841e99784bd98e', 'pca': '', 'source_type': 'chunked document', 'upload_date': '2025-11-28 19:24:52.062381', 'page_lengths': '[1352, 1462, 1842, 401, 1634, 1157, 1138]', 'author': 'Sameer Shroff', 'fullpath': '.\\data\\HW 7 - Design Challenges.pdf', 'modification_date': '2022-10-23 12:31:27.302366', 'N_chunks': 13, 'chunk_idx': 7, 'file_ext': '.pdf', 'basename': 'HW 7 - Design Challenges.pdf', 'creation_date': '2025-11-26 11:27:12.514347', 'source_id': '8a5a4e88-6b39-5898-8682-6953f1a90da7'}, {'page_lengths': '[1352, 1462, 1842, 401, 1634, 1157, 1138]', 'creation_date': '2025-11-26 11:27:12.514347', 'pca': '', 'upload_date': '2025-11-28 19:24:52.062381', 'basename': 'HW 7 - Design Challenges.pdf', 'N_chunks': 13, 'fullpath': '.\\data\\HW 7 - Design Challenges.pdf', 'modification_date': '2022-10-23 12:31:27.302366', 'hash': 'abec6a608c256b197114106e8843696d0ea0cf2fff87109f59841e99784bd98e', 'author': 'Sameer Shroff', 'source_id': '8a5a4e88-6b39-5898-8682-6953f1a90da7', 'chunk_idx': 0, 'source_type': 'chunked document', 'file_ext': '.pdf'}, {'source_type': 'chunked document', 'source_id': '92843a15-ddf5-51b5-b851-ed3b159a4e25', 'author': 'Sameer Shroff', 'creation_date': '2025-11-26 11:27:12.509331', 'upload_date': '2025-11-28 19:24:51.228459', 'basename': 'HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf', 'N_chunks': 8, 'hash': 'b907d592332785225f53963d7e64d3379ba273adfb78baed001d72a0dc604c73', 'fullpath': '.\\data\\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf', 'file_ext': '.pdf', 'modification_date': '2022-09-07 20:37:59.854000', 'pca': '', 'chunk_idx': 2, 'page_lengths': '[2363, 1621, 1323, 682]'}, {'author': 'Sameer Shroff', 'hash': '2c913fd6cc22e915214e21fca277d2db112d01b118af2be89f67edfeafdaf39e', 'upload_date': '2025-11-28 19:24:50.814526', 'pca': '', 'source_id': '3dc8bb69-454a-535c-9815-02ae4e274a4f', 'source_type': 'chunked document', 'chunk_idx': 4, 'N_chunks': 6, 'basename': 'HW 2 - Complex Numbers.pdf', 'file_ext': '.pdf', 'page_lengths': '[1937, 1550, 600]', 'creation_date': '2025-11-26 11:27:12.508334', 'fullpath': '.\\data\\HW 2 - Complex Numbers.pdf', 'modification_date': '2024-08-27 20:24:40.731488'}]], 'distances': [[0.4676171541213989, 0.47722554206848145, 0.6604893207550049, 0.6970309615135193, 0.6977940797805786, 0.7095023393630981, 0.7127243280410767, 0.7267544865608215, 0.7277436852455139, 0.7381874918937683]]}
found 10 similar documents

   distance                                           basename                                    id                 upload_date pca                             source_id         author  chunk_idx                                               hash           modification_date                               page_lengths       source_type                                           fullpath  N_chunks               creation_date file_ext                                           document
0  0.467617                              HW 1 - Cave Flyer.pdf  2df0e1d4-62c2-4ba8-9dac-072608061909  2025-11-28 19:24:50.627433      7353459a-33c2-544c-81f2-4e8877cddfcc  Sameer Shroff          0  d235a1898843e3a439eabc58b387565f659900d5644604...  2024-08-25 16:26:44.119668                           [974, 2735, 291]  chunked document                       .\data\HW 1 - Cave Flyer.pdf         5  2025-11-26 11:27:12.507327     .pdf  Carnegie Mellon University 24-451: Feedback Co...
1  0.477226                              HW 1 - Cave Flyer.pdf  7353459a-33c2-544c-81f2-4e8877cddfcc  2025-11-28 19:24:50.627433      7353459a-33c2-544c-81f2-4e8877cddfcc  Sameer Shroff         -1  d235a1898843e3a439eabc58b387565f659900d5644604...  2024-08-25 16:26:44.119668                           [974, 2735, 291]     full document                       .\data\HW 1 - Cave Flyer.pdf         0  2025-11-26 11:27:12.507327     .pdf  Carnegie Mellon University 24-451: Feedback Co...
2  0.660489                        HW 5 - Exam 1 in Matlab.pdf  243c67fe-7154-4674-a8fd-8223d484fe33  2025-11-28 19:24:51.669425      aca9ef5a-8288-54e0-8231-4268d682efd2  Sameer Shroff          3  910573961d42ea022be07ca314325b4400a963f89e1795...  2024-09-25 17:53:25.497000                         [1749, 2024, 1216]  chunked document                 .\data\HW 5 - Exam 1 in Matlab.pdf         7  2025-11-26 11:27:12.511332     .pdf  j. What happens as K increases?  Show and exam...
3  0.697031  HW 3 - Laplace Transforms and Intro to Control...  cb74c11c-d4d2-4cc3-ac55-f73a76ef73a6  2025-11-28 19:24:51.228459      92843a15-ddf5-51b5-b851-ed3b159a4e25  Sameer Shroff          1  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2022-09-07 20:37:59.854000                    [2363, 1621, 1323, 682]  chunked document  .\data\HW 3 - Laplace Transforms and Intro to ...         8  2025-11-26 11:27:12.509331     .pdf  not discussed in class).   \n4. Typical contro...
4  0.697794              HW 6 - Routh Array and Root Locus.pdf  d3773e72-d96d-4905-930d-0d24df8241e1  2025-11-28 19:24:51.892720      7f0fa013-0289-5477-987f-29511a387622  Sameer Shroff          2  f1e82092a15f30fd7579130c8628ec70ff6926c6171f43...  2023-10-04 17:23:37.193000                                [2191, 957]  chunked document       .\data\HW 6 - Routh Array and Root Locus.pdf         4  2025-11-26 11:27:12.513349     .pdf  Do problems:  \n• # 4.  Hint: for the closed l...
5  0.709502                         HW 2 - Complex Numbers.pdf  2e666691-292c-4b9b-b874-21f3d714abc6  2025-11-28 19:24:50.814526      3dc8bb69-454a-535c-9815-02ae4e274a4f  Sameer Shroff          3  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  2024-08-27 20:24:40.731488                          [1937, 1550, 600]  chunked document                  .\data\HW 2 - Complex Numbers.pdf         6  2025-11-26 11:27:12.508334     .pdf  complex number should you multiply by?  Show t...
6  0.712724                       HW 7 - Design Challenges.pdf  4e110d05-611f-4f6b-bc2e-491ff0897201  2025-11-28 19:24:52.062381      8a5a4e88-6b39-5898-8682-6953f1a90da7  Sameer Shroff          7  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  [1352, 1462, 1842, 401, 1634, 1157, 1138]  chunked document                .\data\HW 7 - Design Challenges.pdf        13  2025-11-26 11:27:12.514347     .pdf  Carnegie Mellon University 24-451: Feedback Co...
7  0.726754                       HW 7 - Design Challenges.pdf  2ed64a78-4324-428b-8c4e-405716135045  2025-11-28 19:24:52.062381      8a5a4e88-6b39-5898-8682-6953f1a90da7  Sameer Shroff          0  abec6a608c256b197114106e8843696d0ea0cf2fff8710...  2022-10-23 12:31:27.302366  [1352, 1462, 1842, 401, 1634, 1157, 1138]  chunked document                .\data\HW 7 - Design Challenges.pdf        13  2025-11-26 11:27:12.514347     .pdf  Carnegie Mellon University 24-451: Feedback Co...
8  0.727744  HW 3 - Laplace Transforms and Intro to Control...  06122fd8-cffe-4a86-9349-a3d8d59dc75f  2025-11-28 19:24:51.228459      92843a15-ddf5-51b5-b851-ed3b159a4e25  Sameer Shroff          2  b907d592332785225f53963d7e64d3379ba273adfb78ba...  2022-09-07 20:37:59.854000                    [2363, 1621, 1323, 682]  chunked document  .\data\HW 3 - Laplace Transforms and Intro to ...         8  2025-11-26 11:27:12.509331     .pdf  inputs and outputs of the function, listed bel...
9  0.738187                         HW 2 - Complex Numbers.pdf  d22c6a9a-689c-447a-a62b-58d5a9db779d  2025-11-28 19:24:50.814526      3dc8bb69-454a-535c-9815-02ae4e274a4f  Sameer Shroff          4  2c913fd6cc22e915214e21fca277d2db112d01b118af2b...  2024-08-27 20:24:40.731488                          [1937, 1550, 600]  chunked document                  .\data\HW 2 - Complex Numbers.pdf         6  2025-11-26 11:27:12.508334     .pdf  𝑐1 + 𝑐2𝑗 by 𝜃 degrees.  Describe your methodol...

In [63]:
query ="what options do I have to install matlab in detail"
response = DS.query(query, k = 10)
print(response.content)

{'ids': [['2df0e1d4-62c2-4ba8-9dac-072608061909', '7353459a-33c2-544c-81f2-4e8877cddfcc', '243c67fe-7154-4674-a8fd-8223d484fe33', 'cb74c11c-d4d2-4cc3-ac55-f73a76ef73a6', '4e110d05-611f-4f6b-bc2e-491ff0897201', 'd3773e72-d96d-4905-930d-0d24df8241e1', '06122fd8-cffe-4a86-9349-a3d8d59dc75f', '42744b23-cac4-40eb-936a-8d31178623c4', '2e666691-292c-4b9b-b874-21f3d714abc6', 'aca9ef5a-8288-54e0-8231-4268d682efd2']], 'embeddings': None, 'documents': [['Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 1: Cave Flyer \n \n \n \nInstructions: \n1) Run MATLAB using one of these methods: \na) Download and install MATLAB locally \n(https://www.cmu.edu/computing/software/all/matlab/). \nb) Run MATLAB online through a browser (https://www.mathworks.com/products/matlab-\nonline.html). \nc) Run MATLAB through a Virtual Andrew session \n(https://www.cmu.edu/computing/services/endpoint/software/managed-\ndesktops/how-to/virtual-andrew.html). \n2) Download the file CaveFly.zip from the course files on Canvas, and unzip \n3) Open MATLAB and navigate to the file.  Add the folder containing the file to the MATLAB \npath (On the toolbar, select Environment | Set Path). \n4) Open the latest version of CaveFly.m. \na) Set the value of M.controller_dir to point to the folder with your controllers \nb) Read the other fields of M and understand the other modifiable parameters \n \n \n \n \n \n \n \n\nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nQuestions: \n1) Your task is to design a controller for the system.  Find the controller file with function  \nfunction F = shroff_controller(y, vy, ytop, ybot) \n \n% Goal - use the input variables to calculate a desired output force F. \n  \n% ytop:  a 1 x 21 vector with positions of the top wall.  ytop(21) is the \nfurthest from the ship. \n% ybot:  a 1 x 21 vector with positions of the bottom wall.  ybot(21) is the \nfurthest from the ship. \n% y: Current position of the ship \n% vy: Current velocity of the ship \n% F: Output force to apply in the vertical direction (can be -1 <= F <= 1, \ncode will enforce this) \n \nRead and understand all of the inputs and output of the function.   \n \n2) In words, describe how you would avoid hitting walls of the cave.  Hint:  You could say \nsomething like if you get within x units of either wall, set F to push the ship the other way.  \nAn alternative scheme would be to try to stay in the middle of the path.   \n3) Convert your scheme to mathematical equations.  Remember, you can only work with the \ninput values in the function F = yourname_controller(ytop, ybot, y, vy).  Add \ncode to the function representing these equations.  Make sure to rename the .m file with \nyour new function name yourname_controller. \n4) Run the code with your controller.  How well did you do?  Describe your process for \nsystematically tuning the controller (for example, how did you use educated guesses to \ntune the strength of forces?).  Try a different control scheme if needed. \n5) Run levels [1, 2, 4, 8, 16, …., 2048] by changing M.levels.  Record the impact time t \nfor each level and take the average.  Report the individual times on the class spreadsheet \n(https://docs.google.com/spreadsheets/d/185q_onHT4oSUj3FxN-12PGQVs_D_wGWYxbHLlN0gWTM/edit?usp=sharing). \n6) In a few sentences describe important factors that were not taken into account in this \nsimulation.  Hint: think about sensor noise, delay in changing the thrust, etc.  Could your \ncontroller be used on different ships?  If the mass of a ship was twice as much, or the cave \nwall shapes were very different (more jagged for example), do you think your controller \nwould have to be adjusted? \n7) Submit answers to these questions as well as controller code on Canvas. \nOptional Upload: \nUpload your controller file here.  We will demo and discuss some of these after the assignment \nis due. \nhttps://forms.gle/pNfxWdQJNpRe6MuE6 \n \n \nOptional Bonus: \nAdd a loop in the code to quickly test your controller on levels [1, 2, 4, 8, …, 2048].  Save the \ntimes in a vector, and take the average.  Try to optimize the average time until collision by \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 3 \nchanging parameter values in your code.  Show that you have found a local minima by \ndemonstrating that by either increasing or decreasing one of the parameters, the average time \ndecreases. \n \n', 'j. What happens as K increases?  Show and example output and qualitatively explain the \nchanges (explain changes in rise time and overshoot). \nk. For part (b), there were several ways to estimate the value of K that results in the plot \ndisplayed.  Using the value of K you calculated on your exam, show the scope output.  \nHow close were you? \nQuestion 7 \nl. Using Matlab (not Simulink), define 𝐺1 and 𝐺2.  Use the commands impulse(), step(), \nand lsim() to recreate the 6 plots.  Review our code examples if you forget how to apply \nan arbitrary input using lsim(). \nQuestion 8 \nm. Use the functions pzmap() and pzplot() to calculate the poles and zeros of G and plot \nthem in the complex plane. \nn. Vary K from 0 to 10 (in increments of .2 or smaller).  Calculate the 2 poles of 𝐺2 for each \nvalue of K (Use a loop to make this easy). \no. Plot the poles as a function of K on the complex plane.  Label 3 regions – (1) when the', 'not discussed in class).   \n4. Typical control systems have requirements on stability, tracking, disturbance rejection, \nand robustness.  Briefly explain each one (hint: Chapter 1 discusses these). \nLaplace Transforms (Section 3.1) \n5. Book problem 3.3 (use a Laplace table) \n6. Book problem 3.7(a) by hand (can use a Laplace table) \n7. Book problem 3.7(d) using Matlab.  Hint: use ilaplace() \n8. Book problem 3.9(a) \n \nSystem Identification \nIdentifying and modeling dynamic systems is often a prerequisite to being able to apply control.  \nIn this case study, you will create models for 10 dynamic systems.  Download file \n“RunExperiment.p” from Canvas, and make sure it is in your working directory.  Understand the \ninputs and outputs of the function, listed below: \n \n>> help RunExperiment \n RunExperiment(id, U, make_plot):  Runs a system simulation for input matrix U \n    inputs:  id: integer from 1 to 10 that sets what system to simulate', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 4 \n \nIf optimizing programmatically, it is much easier using Matlab transfer functions with \nstepinfo() rather than using Simulink.   \n \nMy optimal solution has a rise time of 0.1399 seconds.  Can you beat it? \n \n \n  \n0 0.2 0.4 0.6 0.8 1 1.2 1.4 1.6 1.8 2\n0\n5\n10\n15\n20\n25\n30\n35 Current due to 6*u(t) input', 'Do problems:  \n• # 4.  Hint: for the closed loop transfer function T, sensitivity is defined as \n𝐴\n𝑇 (\n𝑑𝑇\n𝑑𝐴), \n𝑎\n𝑇 (\n𝑑𝑇\n𝑑𝑎), \nor \n𝛽\n𝑇 (\n𝑑𝑇\n𝑑𝛽) for each part, respectively.  Read section 4.1.4 of the textbook for more \ndetails.  You can use the Matlab symbolic toolbox to help with the algebra if necessary.  \n• # 7c only.  Use Simulink.  Hint: 𝐾1 will be in the 1000-1500 range to obtain the desired \nstep overshoot, and the steady state error to 𝑟 = 5𝑡 should be around 0.3.    \n• # 10.  For part (b), you can use Matlab function routh.m found at: \nhttps://www.mathworks.com/matlabcentral/fileexchange/58-routh-m \n• # 29.  Hint: use the Matlab symbolic toolbox to make the algebra trivial. \n \nRoot-Locus Design Method (Chapter 5) \n \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nDo the following book problems .  Note that you can use the Matlab function rlocus( ) for any of', "inputs and outputs of the function, listed below: \n \n>> help RunExperiment \n RunExperiment(id, U, make_plot):  Runs a system simulation for input matrix U \n    inputs:  id: integer from 1 to 10 that sets what system to simulate \n             U:  [Nt x Nu] input matrix, where Nt is the number of \n             timepoints and Nu is the number of inputs for the system. \n             Each column is a input signal. \n             make_plot: Boolean for if a plot should be generated \n    outputs: X:  [Nt x Nx] output matrix, where Nt is the number of \n             timepoints and Nx is the number of states.  Each column is how that \n             state evolves with time. \n \n  For example, to run system 5 with a step input, we could write something like \n \nt = (0:.1:10)'; \nU = ones(length(t), 1).*heaviside(t-5); \nX = RunExperiment(5, U, true); \n \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2", 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 5 \n \nIn this homework, you will revisit questions on Exam 1 and make use of Matlab and Simulink to \nanalyze the systems in more detail.  \n \nQuestion 1 \na) Recreate the system in Matlab or Simulink. \nb) For various positive values of k, show the effect of a unit step disturbance by plotting \nthe system output vs. time (ideally all on the same graph with a legend).    \nc) Do your analytical solutions on the Exam (for steady-state value, time constant) match \nwhat you see in the simulations?  \n \nQuestion 2 \na. Recreate the model shown in Question 2 in Simulink.   \nb. On the plot displayed on the scope, label the system specifications listed in the bullet \npoints. \nNote: If you want “nicer” plots, you can use the XY Graph feature, or send both t and y \nout to the workspace (under “Sinks”) and use the Matlab plot(t,y) command.  For a', 'complex number should you multiply by?  Show this works using Matlab. \n \nNewton’s Method \nNewton’s method can be used to find the roots of a function.  One starts with an initial guess \n𝑥0.  The guess is updated as  \n𝑥𝑛+1 = 𝑥𝑛 − 𝑓(𝑥𝑛)\n𝑓′(𝑥𝑛) \n \n8. Consider the polynomial  \n𝑓(𝑥) = 𝑥3 + 1 \na. Use the Matlab command roots() to find the roots of the polynomial (𝑝1, 𝑝2, 𝑝3). \nb. Analytically compute 𝑓′(𝑥). \nc. Pick a starting value 𝑥0,1 from the complex plane and show it converges to root  \n𝑝1 using Newton’s method.  Similarly show different starting values 𝑥0,2 and 𝑥0,3 \nconverge to 𝑝2 and 𝑝3, respectively.  Plot each sequence of values 𝑥𝑛,𝑖 in the \ncomplex plane and show they terminate at 𝑝𝑖. \nOptional Bonus Problems:  \n9. You wish to first scale the shape by factor 𝛼 and then rotate it about an arbitrary point \n𝑐1 + 𝑐2𝑗 by 𝜃 degrees.  Describe your methodology (equations) for doing this using \ncomplex algebra, and show it works in Matlab for 𝛼 = 2, 𝑐1 = 3, 𝑐2 = 1, 𝜃 = 30°.', 'Carnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 1 \nHomework 5 \n \nIn this homework, you will revisit questions on Exam 1 and make use of Matlab and Simulink to \nanalyze the systems in more detail.  \n \nQuestion 1 \na) Recreate the system in Matlab or Simulink. \nb) For various positive values of k, show the effect of a unit step disturbance by plotting \nthe system output vs. time (ideally all on the same graph with a legend).    \nc) Do your analytical solutions on the Exam (for steady-state value, time constant) match \nwhat you see in the simulations?  \n \nQuestion 2 \na. Recreate the model shown in Question 2 in Simulink.   \nb. On the plot displayed on the scope, label the system specifications listed in the bullet \npoints. \nNote: If you want “nicer” plots, you can use the XY Graph feature, or send both t and y \nout to the workspace (under “Sinks”) and use the Matlab plot(t,y) command.  For a \nmass-spring-damper system with no feedback, this would look something like this: \n \nc. Calculate the final value of y analytically if the input to the system is a step of \nmagnitude 𝑘1 (𝑓(𝑡) = 𝑘1𝜇(𝑡)).  Show that your Simulink model gives the same results \nfor a few values of 𝑘1. \nd. Show that the rise time, settling time, % overshoot, and peak time are not affected by \n𝑘1 using your Simulink model.  Prove this analytically as well. \nQuestion 3 \ne. Define a transfer function 𝐺(𝑠) that has 2 imaginary poles {+2j, -2j} using G = zpk(…).  \nSee our code examples if you forgot how to do this.  Show the impulse response over a \nperiod of 10 seconds using impulse(G, 10).  Explain the response, and compare to the \nanalytical solution (calculate the period and frequency analytically and compare). \n\nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 2 \nf. Define a transfer function 𝐺(𝑠) that has 2 real poles {-1, -2}.  Determine the analytical \nresponse to an impulse.  Compare your result to impulse(G, 10).   \ng. Define a transfer function 𝐺(𝑠) that has 2 complex conjugate poles (-1±j) in the left \nhalf plane.  Move the poles to the left (𝐺2(𝑠)) and further away from the x-axis (𝐺3(𝑠)).  \nPlot the impulse response for all 3 cases on the same figure and explain the output. \nQuestion 5 \nh. Recreate the system in Simulink. \ni. Use the value of K calculated in the exam that makes the rise time less than 1 and show \nthe output on the scope.  Is it what you expected? \nj. What happens as K increases?  Show and example output and qualitatively explain the \nchanges (explain changes in rise time and overshoot). \nk. For part (b), there were several ways to estimate the value of K that results in the plot \ndisplayed.  Using the value of K you calculated on your exam, show the scope output.  \nHow close were you? \nQuestion 7 \nl. Using Matlab (not Simulink), define 𝐺1 and 𝐺2.  Use the commands impulse(), step(), \nand lsim() to recreate the 6 plots.  Review our code examples if you forget how to apply \nan arbitrary input using lsim(). \nQuestion 8 \nm. Use the functions pzmap() and pzplot() to calculate the poles and zeros of G and plot \nthem in the complex plane. \nn. Vary K from 0 to 10 (in increments of .2 or smaller).  Calculate the 2 poles of 𝐺2 for each \nvalue of K (Use a loop to make this easy). \no. Plot the poles as a function of K on the complex plane.  Label 3 regions – (1) when the \npoles are complex and on the right-half plane, (2) when the poles are complex and on \nthe left-half plane, and (3) when the poles are real (on the x-axis).  On your plot, include \nthe value of K and values for the poles that divide the regions.  Draw arrows showing \nthe direction of how the poles move for increasing K. \nHint: your plot should look something like this: \n \nCarnegie Mellon University 24-451: Feedback Control Systems \n Instructor: Dr. Sameer Shroff \n 3 \n \np. Calculate the boundaries of the 3 regions analytically by considering that a polynomial \nof the form 𝑎𝑥2 +𝑏𝑥 +𝑐 = 0 has roots \n−𝑏 ±√𝑏2 −4𝑎𝑐\n2𝑎  \nand examining when 𝑏2 −4𝑎𝑐 > 0, for example. \nq. Show that as K goes to infinity, the real poles stay on the left-half plane by (i) using a \nvery large value of K in your code and (ii) proving analytically.  What are the 2 poles at \nthis limit?  \nr. Consider the region where the poles are complex conjugates on the LHP.  As K \nincreases, what happens to the damping ratio, natural frequency, and damped natural \nfrequency?  What is happening to the % overshoot, rise time, and settling time? \ns. Consider the region where the poles are real on the LHP.  What happens as K \nincreases?  Remember, there are 2 first-order poles, so there will be two time \nconstants.  Does increasing K decrease the overall settling time of the system?  \nt. Consider all regions.  What value of K gives the shortest settling time overall?  Show \nthis by plotting the system response to a unit step for this value of K and for values of K \nabove and below this value on the same plot. \n \n\n']], 'uris': None, 'included': ['metadatas', 'documents', 'distances'], 'data': None, 'metadatas': [[{'file_ext': '.pdf', 'chunk_idx': 0, 'N_chunks': 5, 'hash': 'd235a1898843e3a439eabc58b387565f659900d564460438304b195186542fe6', 'basename': 'HW 1 - Cave Flyer.pdf', 'source_id': '7353459a-33c2-544c-81f2-4e8877cddfcc', 'author': 'Sameer Shroff', 'creation_date': '2025-11-26 11:27:12.507327', 'modification_date': '2024-08-25 16:26:44.119668', 'page_lengths': '[974, 2735, 291]', 'upload_date': '2025-11-28 19:24:50.627433', 'source_type': 'chunked document', 'fullpath': '.\\data\\HW 1 - Cave Flyer.pdf', 'pca': ''}, {'chunk_idx': -1, 'file_ext': '.pdf', 'hash': 'd235a1898843e3a439eabc58b387565f659900d564460438304b195186542fe6', 'fullpath': '.\\data\\HW 1 - Cave Flyer.pdf', 'N_chunks': 0, 'source_type': 'full document', 'source_id': '7353459a-33c2-544c-81f2-4e8877cddfcc', 'creation_date': '2025-11-26 11:27:12.507327', 'upload_date': '2025-11-28 19:24:50.627433', 'pca': '', 'page_lengths': '[974, 2735, 291]', 'modification_date': '2024-08-25 16:26:44.119668', 'basename': 'HW 1 - Cave Flyer.pdf', 'author': 'Sameer Shroff'}, {'basename': 'HW 5 - Exam 1 in Matlab.pdf', 'author': 'Sameer Shroff', 'modification_date': '2024-09-25 17:53:25.497000', 'N_chunks': 7, 'page_lengths': '[1749, 2024, 1216]', 'file_ext': '.pdf', 'source_id': 'aca9ef5a-8288-54e0-8231-4268d682efd2', 'chunk_idx': 3, 'fullpath': '.\\data\\HW 5 - Exam 1 in Matlab.pdf', 'pca': '', 'hash': '910573961d42ea022be07ca314325b4400a963f89e1795c1b5ed92d7968b9d54', 'creation_date': '2025-11-26 11:27:12.511332', 'source_type': 'chunked document', 'upload_date': '2025-11-28 19:24:51.669425'}, {'basename': 'HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf', 'creation_date': '2025-11-26 11:27:12.509331', 'page_lengths': '[2363, 1621, 1323, 682]', 'chunk_idx': 1, 'source_id': '92843a15-ddf5-51b5-b851-ed3b159a4e25', 'source_type': 'chunked document', 'hash': 'b907d592332785225f53963d7e64d3379ba273adfb78baed001d72a0dc604c73', 'upload_date': '2025-11-28 19:24:51.228459', 'file_ext': '.pdf', 'author': 'Sameer Shroff', 'fullpath': '.\\data\\HW 3 - Laplace Transforms and Intro to Controls and System ID.pdf', 'pca': '', 'N_chunks': 8, 'modification_date': '2022-09-07 20:37:59.854000'}, {'upload_date': '2025-11-28 19:24:52.062381', 'pca': '', 'source_type': 'chunked document', 'page_lengths': '[1352, 1462, 1842, 401, 1634, 1157, 1138]', 'creation_date': '2025-11-26 11:27:12.514347', 'file_ext': '.pdf', 'N_chunks': 13, 'hash': 'abec6a608c256b197114106e8843696d0ea0cf2fff87109f59841e99784bd98e', 'basename': 'HW 7 - Design Challenges.pdf', 'author': 'Sameer Shroff', 'fullpath': '.\\data\\HW 7 - Design Challenges.pdf', 'source_id': '8a5a4e88-6b39-5898-8682-6953f1a90da7', 'modification_date': '2022-10-23 12:31:27.302366', 'chunk_idx': 7}, {'fullpath': '.\\data\\HW 6 - Routh Array and Root Locus.pdf', 'hash': 'f1e82092a15f30fd7579130c8628ec70ff6926c6171f43166a0f01edbb9cf0f1', 'source_id': '7f0fa013-0289-5477-987f-29511a387622', 'author': 'Sameer Shroff', 'creation_date': '2025-11-26 11:27:12.513349', 'file_ext': '.pdf', 'upload_date': '2025-11-28 19:24:51.89272

In [64]:
DS.compute_pca()

embeddings matrix is (59, 384)
pca matrix is (59, 59)
saved pca data to vector database

In [65]:
labels, inertia, df_pca = DS.run_kmeans(n_clusters = 3)
df_pca

                                         pca_0     pca_1     pca_2     pca_3     pca_4     pca_5     pca_6     pca_7     pca_8     pca_9    pca_10    pca_11    pca_12    pca_13    pca_14    pca_15    pca_16    pca_17    pca_18    pca_19    pca_20    pca_21    pca_22    pca_23    pca_24    pca_25    pca_26    pca_27    pca_28    pca_29    pca_30    pca_31    pca_32    pca_33    pca_34    pca_35    pca_36    pca_37    pca_38    pca_39    pca_40    pca_41    pca_42    pca_43    pca_44    pca_45    pca_46    pca_47    pca_48    pca_49    pca_50    pca_51    pca_52    pca_53    pca_54    pca_55    pca_56  pca_57  pca_58
7353459a-33c2-544c-81f2-4e8877cddfcc -0.097473  0.023911  0.404297  0.123596 -0.044678 -0.191650 -0.105103  0.284668  0.090149  0.191895  0.212036  0.049622  0.157959 -0.012924 -0.103882 -0.110474 -0.038361  0.108032  0.043884 -0.095276  0.120422 -0.054108 -0.064026 -0.006313 -0.025238 -0.047363 -0.026718  0.067017  0.056427 -0.009048  0.030624  0.017227  0.001927  0.021255 -0.014137 -0.010353  0.017822  0.005661 -0.017075 -0.024445 -0.011375 -0.004311 -0.007507  0.016754  0.008163  0.004921 -0.009583  0.005924 -0.012108 -0.001997  0.002077 -0.002522  0.007568  0.013435  0.026901  0.038269  0.001522    -0.0     0.0
3dc8bb69-454a-535c-9815-02ae4e274a4f  0.379395 -0.236328  0.203735  0.020264 -0.132568  0.264648  0.022995  0.056427 -0.270508 -0.085876  0.068726 -0.038147 -0.092590 -0.161377 -0.008499 -0.092163 -0.024323 -0.068298  0.068970  0.008553 -0.041504 -0.010902 -0.028015  0.110962  0.002043  0.084778 -0.042358  0.046265  0.038239 -0.023895  0.049133  0.064575 -0.064758 -0.031403  0.049225 -0.031204  0.032715  0.003504  0.002792  0.024887  0.004379 -0.043365  0.014145  0.024796 -0.032166 -0.012032 -0.008881 -0.001143  0.004749 -0.000172  0.002567 -0.003546 -0.002533 -0.001260  0.005260  0.000632 -0.023254    -0.0     0.0
92843a15-ddf5-51b5-b851-ed3b159a4e25 -0.202026 -0.345703  0.504883  0.128418 -0.142334 -0.077881  0.184692 -0.223999  0.110291  0.186401 -0.299072 -0.084412 -0.107727  0.054596 -0.072449 -0.065063  0.035095  0.046326  0.080017  0.066284 -0.043060  0.013184  0.049896 -0.003101  0.000798 -0.000573 -0.016876 -0.018890 -0.021057  0.005207  0.005890 -0.016312 -0.001168  0.018341  0.025421  0.013672 -0.002172 -0.024200 -0.015480  0.012848 -0.001431  0.007488 -0.011650 -0.005959  0.016541 -0.009270  0.020523  0.005798  0.009270 -0.054596  0.050201 -0.039642  0.044678  0.002205 -0.003706 -0.002375  0.000022    -0.0     0.0
eb7dbac7-1c3e-59c6-ba88-06afd7217d81 -0.147705 -0.039734  0.125000 -0.253174 -0.197144  0.105835 -0.268555 -0.065979  0.044342 -0.213501  0.076904 -0.341064  0.032623 -0.042175  0.004562 -0.058899  0.076111  0.081421 -0.123230 -0.022675  0.030365 -0.037170 -0.016342  0.031982  0.079956 -0.078674 -0.041473 -0.073425 -0.057800  0.032593  0.004246  0.001627  0.018616  0.034302  0.023117  0.007957 -0.048462 -0.006432 -0.014511 -0.010651  0.017853 -0.003691 -0.001976 -0.008224 -0.000726 -0.004879 -0.014091  0.002180 -0.000116  0.006020  0.001966 -0.001649  0.001304 -0.000312 -0.000065 -0.000304  0.000169    -0.0    -0.0
aca9ef5a-8288-54e0-8231-4268d682efd2 -0.190430 -0.133057 -0.096863 -0.204712 -0.094116 -0.157104  0.200562  0.118103 -0.053558  0.097595 -0.009293 -0.133301  0.066956  0.013596  0.152466  0.131104 -0.050476 -0.009880  0.058533 -0.105652 -0.065857 -0.055542 -0.013664  0.111450  0.010101  0.001257  0.003708  0.022827 -0.022614  0.040436  0.016708 -0.012489  0.084595 -0.067810 -0.031738  0.078003 -0.007553  0.028473  0.023453 -0.015717  0.018524 -0.022537 -0.005428  0.002623 -0.041077 -0.027939 -0.008636  0.031586  0.000028 -0.067871  0.026489  0.004845 -0.064209 -0.003679  0.000682  0.002855  0.000837    -0.0     0.0
7f0fa013-0289-5477-987f-29511a387622 -0.123108 -0.272949 -0.099243 -0.112366 -0.015457 -0.017975 -0.184204 -0.045715 -0.048340 -0.075684 -0.106812  0.147217 -0.056030  0.073364 -0.156006  0.125366 -0.193115 -0.020279 -0.123047 -0.074402  0.021027 -0.007038 -0.014282  0.062103 -0.140259  0.019592 -0.103699  0.032104  0.046173  0.079285  0.013756 -0.014771  0.014153  0.022018  0.014580  0.000215 -0.041290 -0.050598 -0.011856  0.025299 -0.027969  0.012009  0.002075 -0.027939  0.030029  0.027374 -0.002907  0.010834  0.015060 -0.012421 -0.064880 -0.064270 -0.016495  0.004490  0.000653 -0.000857 -0.000174    -0.0     0.0
8a5a4e88-6b39-5898-8682-6953f1a90da7 -0.033386 -0.207031 -0.095337  0.043060  0.011024 -0.074829 -0.091003  0.202393 -0.097473 -0.097839 -0.120789  0.020432  0.024307  0.088562  0.053894 -0.118774  0.101746 -0.012848 -0.016586  0.120972  0.045227  0.047791 -0.009941  0.044128 -0.005047  0.012871  0.116638 -0.014740  0.011490  0.044098 -0.018387 -0.015388  0.054382  0.053192  0.036530  0.016083  0.037842 -0.010239  0.002043  0.036163  0.002337 -0.004742 -0.046722  0.027618  0.010063  0.012650 -0.027008 -0.091064 -0.038635 -0.060669 -0.053192  0.037445  0.017197  0.010063 -0.019028  0.009598 -0.001311    -0.0     0.0
b58c24f9-36c9-5332-8d5c-c363e1ab26be -0.012215 -0.343262 -0.161011  0.113770  0.010155 -0.145142 -0.020691 -0.105591 -0.008057 -0.076477  0.068481  0.179077  0.081726 -0.161377  0.141479 -0.049103  0.051117  0.086365  0.042786 -0.022949 -0.054474  0.016586  0.033752 -0.076294  0.037201 -0.097900 -0.115356  0.004154  0.019638 -0.060638 -0.077209 -0.047363  0.025330 -0.026367  0.049133 -0.017288 -0.020538  0.021561 -0.036255  0.050781 -0.030807  0.000293  0.004009 -0.019684 -0.009697 -0.035248 -0.018814  0.011269 -0.008797 -0.031860 -0.027328  0.019409  0.014427 -0.008537  0.037567 -0.023300  0.001309    -0.0     0.0
0eacdba8-9efd-59ce-816a-366d8cf519a9 -0.171631 -0.300293 -0.043915  0.240723  0.167114 -0.070374  0.006599 -0.133789 -0.120117  0.056091  0.248901 -0.097595  0.010117 -0.054474 -0.038605  0.197998  0.075989  0.063232 -0.047119  0.128052  0.081299  0.087097  0.083008 -0.035797 -0.006756  0.061157  0.020676 -0.008873  0.012238  0.024933  0.024551  0.037628 -0.031372 -0.009079 -0.001306  0.029282 -0.000233  0.020813  0.015388 -0.058655 -0.011139  0.008575 -0.007175  0.008621 -0.006001  0.032623  0.010651 -0.009827  0.011314 -0.005291 -0.010109 -0.003567  0.005573 -0.059906 -0.002028  0.013710  0.000299    -0.0     0.0